<a href="https://colab.research.google.com/github/rajeshxdatascience/SpecLens-AI/blob/main/SpecLens_AI_Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import pandas as pd
import numpy as np
import re

In [96]:
pd.set_option('display.max_columns',None)
pd.set_option('display.width',None)
pd.set_option('display.max_colwidth',None)

In [97]:
df = pd.read_csv('/content/new_smartphones_columns_for_ml.csv')

In [98]:
df.head()

,model_id,model,beebome_score,rating,rating_count,market_status,launch_on,old_price,price,launch_price,display_type,display_size,display_res,body_dimension,weight,body_front,body_back,body_side,build_quality,ports,ip_rating,speaker,chipset,cpu,gpu,main_cam,main_cam2,main_cam3,main_cam_features,main_video,os,software_updates,ai_features,front_cam,front_cam_features,front_video,battery,charging,storage,ram,sim,tech,2g,3g,4g,5g,speed,wifi,bluetooth,positioning_system,nfc,finger_print,sensors,add_features,flipkart_buy_link,amazon_buy_link,official_store_link
0,1,Apple iPhone 14 (6GB + 256GB),69,4.6,(321KRatings),In Stock,07 Sep 2022,"Was ₹56,999 2 day(s) ago Was ₹56,999 2 day(s) ago","₹64,900","₹79,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.1 inches, 90.2 cm², 86% Screen To Body Ratio","FHD+, 1170 x 2532 pixels, 19.5:9 (460 ppi), 8-bit colours, 82% DCI-P3, 1200 nits(Peak Brightness), 2000000:1 Contrast Ratio",146.7 x 71.5 x 7.8 mm,172 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR, Stereo Sound Recording",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","3279 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","256GB, NvMe","6GB, LPDDR4X",nano-SIM and eSIM,"5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100, CDMA2000 1xEV-DO (6 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-starlight-256-gb/p/itmaeda15697bb79?pid=MOBGHWFHBJGZYRZC&lid=LSTMOBGHWFHBJGZYRZCUALABX&marketplace=FLIPKART&q=iphone+14+&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=organic&iid=d16ab4a6-25f4-4cb9-8d77-ecbd3f8a6a54.MOBGHWFHBJGZYRZC.SEARCH&ppt=pp&ppn=pp&ssid=kueh4gc0g00000001729242962911&qH=e683ba9749683369&affid=contactbe1,https://www.amazon.in/dp/B0BDJS3MRM?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN
1,2,Apple iPhone 14 (6GB + 512GB),69,4.6,(321KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹89,900","₹79,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.1 inches, 90.2 cm², 86% Screen To Body Ratio","FHD+, 1170 x 2532 pixels, 19.5:9 (460 ppi), 8-bit colours, 82% DCI-P3, 1200 nits(Peak Brightness), 2000000:1 Contrast Ratio",146.7 x 71.5 x 7.8 mm,172 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR, Stereo Sound Recording",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","3279 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","512GB, NvMe","6GB, LPDDR4X",nano-SIM and eSIM,"5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100, CDMA2000 1xEV-DO (6 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-midnight-512-gb/p/itm01540a8ff03de?pid=MOBGHWFHBEMUZSBY&lid=LSTMOBGHWFHBEMUZSBYWJC9VQ&marketplace=FLIPKART&q=iphone+14+&store=tyy%2F4io&srno=s_1_5&otracker=search&otracker1=search&fm=organic&iid=d16ab4a6-25f4-4cb9-8d77-ecbd3f8a6a54.MOBGHWFHBEMUZSBY.SEARCH&ppt=pp&ppn=pp&ssid=kueh4gc0g00000001729242962911&qH=e683ba9749683369&affid=contactbe1,https://www.amazon.in/dp/B0BDJGX2XZ?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN
2,3,Apple iPhone 14 Plus (6GB + 256GB),72,4.6,(87KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹79,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","256GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-starlight-256-gb/p/itm8ee001dd954a2?pid=MOBGHWFHQGM9B4EU&lid=LSTMOBGHWFHQGM9B4EUGHBHUP&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_4&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHQGM9B4EU.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,NaN,NaN
3,4,Apple iPhone 14 Plus (6GB + 512GB),72,4.6,(87KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹99,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","512GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-blue-512-gb/p/itm9b829cc08a732?pid=MOBGHWFHKHPYMQX8&lid=LSTMOBGHWFHKHPYMQX8K7QHSJ&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_7&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHKHPYMQX8.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,NaN,NaN
4,5,Apple iPhone 14 Plus,72,4.6,(87KRatings),In Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹69,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","128GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-starlight-128-gb/p/itmc922ddc8af349?pid=MOBGHWFHVCB2YZYR&lid=LSTMOBGHWFHVCB2YZYRBDOEVN&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_3&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHVCB2YZYR.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,https://www.amazon.in/dp/B0BDJFTGK6?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 57 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    object
 5   market_status        1268 non-null   object
 6   launch_on            1268 non-null   object
 7   old_price            1149 non-null   object
 8   price                1268 non-null   object
 9   launch_price         1268 non-null   object
 10  display_type         1268 non-null   object
 11  display_size         1268 non-null   object
 12  display_res          1268 non-null   object
 13  body_dimension       1268 non-null   object
 14  weight               1268 non-null   object
 15  body_front           1268 non-null   object
 16  body_back            1238 non-null   object
 17  body_side            1251 non-null   object
 18  build_quality        739 non-null    object
 19  ports                1268 non-null   object
 20  ip_rating            915 non-null    object
 21  speaker              1265 non-null   object
 22  chipset              1268 non-null   object
 23  cpu                  1268 non-null   object
 24  gpu                  1250 non-null   object
 25  main_cam             1268 non-null   object
 26  main_cam2            1214 non-null   object
 27  main_cam3            631 non-null    object
 28  main_cam_features    1268 non-null   object
 29  main_video           1239 non-null   object
 30  os                   1268 non-null   object
 31  software_updates     1228 non-null   object
 32  ai_features          780 non-null    object
 33  front_cam            1268 non-null   object
 34  front_cam_features   1026 non-null   object
 35  front_video          1229 non-null   object
 36  battery              1268 non-null   object
 37  charging             1268 non-null   object
 38  storage              1268 non-null   object
 39  ram                  1268 non-null   object
 40  sim                  1264 non-null   object
 41  tech                 1200 non-null   object
 42  2g                   1262 non-null   object
 43  3g                   1264 non-null   object
 44  4g                   1267 non-null   object
 45  5g                   1028 non-null   object
 46  speed                1264 non-null   object
 47  wifi                 1268 non-null   object
 48  bluetooth            1266 non-null   object
 49  positioning_system   1268 non-null   object
 50  nfc                  595 non-null    object
 51  finger_print         1192 non-null   object
 52  sensors              1268 non-null   object
 53  add_features         469 non-null    object
 54  flipkart_buy_link    1085 non-null   object
 55  amazon_buy_link      724 non-null    object
 56  official_store_link  610 non-null    object
dtypes: float64(1), int64(2), object(54)
memory usage: 564.8+ KB

In [100]:
df['brand'] = df['model'].str.lower().str.split(' ').str.get(0)

In [101]:
df['brand'].value_counts()

brand
realme      231
samsung     196
vivo        177
oppo        100
redmi        93
iqoo         74
poco         70
infinix      61
oneplus      59
apple        54
motorola     40
moto         38
google       20
nothing      18
xiaomi       18
honor        10
asus          5
cmf           4
Name: count, dtype: int64

In [102]:
df.loc[df['brand'].str.contains('moto'),'brand'] = 'motorola'

In [103]:
df['brand'].value_counts()

brand
realme      231
samsung     196
vivo        177
oppo        100
redmi        93
motorola     78
iqoo         74
poco         70
infinix      61
oneplus      59
apple        54
google       20
nothing      18
xiaomi       18
honor        10
asus          5
cmf           4
Name: count, dtype: int64

In [104]:
df['brand'].count()

np.int64(1268)

In [105]:
df['brand'] = df['brand'].astype('category')

In [106]:
df['beebome_score'].value_counts()

beebome_score
80    57
73    45
84    41
74    41
68    37
      ..
47     4
28     3
26     3
29     2
22     1
Name: count, Length: 70, dtype: int64

In [107]:
df['rating'].value_counts()

rating
4.3    299
4.4    271
4.2    236
4.5    134
4.1     92
4.6     70
4.7     46
4.8     29
4.0     29
2.0     16
3.9     15
1.0     12
3.8      5
3.4      5
3.5      2
3.7      2
3.6      2
5.0      1
4.9      1
3.0      1
Name: count, dtype: int64

In [108]:
df['rating_count'] = df['rating_count'].str.lower().str.split('r').str.get(0)

In [109]:
df['rating_count'] = df['rating_count'].str.replace('(','')

In [110]:
df['rating_count'] = df['rating_count'].str.replace('k',"1000")

In [111]:
df['rating_count'] = df['rating_count'].astype('float64')

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   market_status        1268 non-null   object
 6   launch_on            1268 non-null   object
 7   old_price            1149 non-null   object
 8   price                1268 non-null   object
 9   launch_price         1268 non-null   object
 10  display_type         1268 non-null   object
 11  display_size         1268 non-null   object
 12  display_res          1268 non-null   object
 13  body_dimension       1268 non-null   object
 14  weight               1268 non-null   object
 15  body_front           1268 non-null   object
 16  body_back            1238 non-null   object
 17  body_side            1251 non-null   object
 18  build_quality        739 non-null    object
 19  ports                1268 non-null   object
 20  ip_rating            915 non-null    object
 21  speaker              1265 non-null   object
 22  chipset              1268 non-null   object
 23  cpu                  1268 non-null   object
 24  gpu                  1250 non-null   object
 25  main_cam             1268 non-null   object
 26  main_cam2            1214 non-null   object
 27  main_cam3            631 non-null    object
 28  main_cam_features    1268 non-null   object
 29  main_video           1239 non-null   object
 30  os                   1268 non-null   object
 31  software_updates     1228 non-null   object
 32  ai_features          780 non-null    object
 33  front_cam            1268 non-null   object
 34  front_cam_features   1026 non-null   object
 35  front_video          1229 non-null   object
 36  battery              1268 non-null   object
 37  charging             1268 non-null   object
 38  storage              1268 non-null   object
 39  ram                  1268 non-null   object
 40  sim                  1264 non-null   object
 41  tech                 1200 non-null   object
 42  2g                   1262 non-null   object
 43  3g                   1264 non-null   object
 44  4g                   1267 non-null   object
 45  5g                   1028 non-null   object
 46  speed                1264 non-null   object
 47  wifi                 1268 non-null   object
 48  bluetooth            1266 non-null   object
 49  positioning_system   1268 non-null   object
 50  nfc                  595 non-null    object
 51  finger_print         1192 non-null   object
 52  sensors              1268 non-null   object
 53  add_features         469 non-null    object
 54  flipkart_buy_link    1085 non-null   object
 55  amazon_buy_link      724 non-null    object
 56  official_store_link  610 non-null    object
 57  brand                1268 non-null   category
dtypes: category(1), float64(2), int64(2), object(53)
memory usage: 566.7+ KB

In [113]:
df['market_status'].value_counts()

market_status
In Stock        896
Out of Stock    372
Name: count, dtype: int64

In [114]:
def market(text):

  t = text.lower()

  if t == 'in stock':
    return 1
  elif t == 'out of stock':
    return 0

df['is_available'] = df['market_status'].apply(market)

In [115]:
df['is_available'].value_counts()

is_available
1    896
0    372
Name: count, dtype: int64

In [116]:
df.drop(columns='market_status',inplace=True)

In [117]:
df['launch_on']

0       07 Sep 2022
1       07 Sep 2022
2       07 Sep 2022
3       07 Sep 2022
4       07 Sep 2022
           ...
1263    07 Mar 2024
1264    11 Mar 2025
1265    11 Mar 2025
1266    09 May 2023
1267    09 May 2023
Name: launch_on, Length: 1268, dtype: object

In [118]:
df['launch_on'] = pd.to_datetime(df['launch_on'])

In [119]:
df['launch_on']

0      2022-09-07
1      2022-09-07
2      2022-09-07
3      2022-09-07
4      2022-09-07
          ...
1263   2024-03-07
1264   2025-03-11
1265   2025-03-11
1266   2023-05-09
1267   2023-05-09
Name: launch_on, Length: 1268, dtype: datetime64[ns]

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            1149 non-null   object
 7   price                1268 non-null   object
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(2), int64(3), object(51)
memory usage: 566.7+ KB

In [121]:
df['old_price'].value_counts()

old_price
Lowest price since launch Lowest price since launch      305
Was ₹7,999 2 month(s) ago Was ₹7,999 2 month(s) ago        8
Was ₹15,999 2 month(s) ago Was ₹15,999 2 month(s) ago      8
Was ₹22,999 2 month(s) ago Was ₹22,999 2 month(s) ago      7
Was ₹13,999 2 month(s) ago Was ₹13,999 2 month(s) ago      7
                                                        ...
Was ₹47,839 22 day(s) ago Was ₹47,839 22 day(s) ago        1
Was ₹25,999 2 month(s) ago Was ₹25,999 2 month(s) ago      1
Was ₹34,999 10 day(s) ago Was ₹34,999 10 day(s) ago        1
Was ₹23,799 5 day(s) ago Was ₹23,799 5 day(s) ago          1
Was ₹21,300 1 month(s) ago Was ₹21,300 1 month(s) ago      1
Name: count, Length: 667, dtype: int64

In [122]:
df['old_price'] = df['old_price'].str.lower().str.split(' ').str.get(1)

In [123]:
df.loc[df['old_price'] == 'price','old_price'] = np.nan

In [124]:
df['old_price'].value_counts(dropna=False)

old_price
NaN        424
₹11,999     18
₹9,999      16
₹22,999     16
₹10,999     15
          ...
₹13,898      1
₹12,754      1
₹11,874      1
₹11,450      1
₹22,319      1
Name: count, Length: 448, dtype: int64

In [125]:
df['old_price'] = df['old_price'].str.replace('₹','')

In [126]:
df['old_price'] = df['old_price'].str.replace(',','')

In [127]:
df['old_price'] = df['old_price'].astype('float')

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   object
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(3), object(50)
memory usage: 566.7+ KB

In [129]:
df['price'] = df['price'].str.replace('₹','')

In [130]:
df['price'] = df['price'].str.replace(',','')

In [131]:
df['price'] = df['price'].astype('int')

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   int64
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(4), object(49)
memory usage: 566.7+ KB

In [133]:
df['launch_price'] = df['launch_price'].str.replace('₹','').str.replace(',','').astype(int)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   int64
 8   launch_price         1268 non-null   int64
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(5), object(48)
memory usage: 566.7+ KB

In [135]:
df['is_flipkart_available'] = df['flipkart_buy_link'].notna().astype('int')

In [136]:
df['is_flipkart_available'].value_counts()

is_flipkart_available
1    1085
0     183
Name: count, dtype: int64

In [137]:
df['is_amazon_available'] = df['amazon_buy_link'].notna().astype('int')

In [138]:
df['is_amazon_available'].value_counts()

is_amazon_available
1    724
0    544
Name: count, dtype: int64

In [139]:
df['is_official_available'] = df['official_store_link'].notna().astype('int')

In [140]:
df['is_official_available'].value_counts()

is_official_available
0    658
1    610
Name: count, dtype: int64

In [141]:
df.drop(columns=['flipkart_buy_link','amazon_buy_link','official_store_link'],inplace=True)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model_id               1268 non-null   int64
 1   model                  1268 non-null   object
 2   beebome_score          1268 non-null   int64
 3   rating                 1268 non-null   float64
 4   rating_count           994 non-null    float64
 5   launch_on              1268 non-null   datetime64[ns]
 6   old_price              844 non-null    float64
 7   price                  1268 non-null   int64
 8   launch_price           1268 non-null   int64
 9   display_type           1268 non-null   object
 10  display_size           1268 non-null   object
 11  display_res            1268 non-null   object
 12  body_dimension         1268 non-null   object
 13  weight                 1268 non-null   object
 14  body_front             1268 non-null   object
 15  body_back              1238 non-null   object
 16  body_side              1251 non-null   object
 17  build_quality          739 non-null    object
 18  ports                  1268 non-null   object
 19  ip_rating              915 non-null    object
 20  speaker                1265 non-null   object
 21  chipset                1268 non-null   object
 22  cpu                    1268 non-null   object
 23  gpu                    1250 non-null   object
 24  main_cam               1268 non-null   object
 25  main_cam2              1214 non-null   object
 26  main_cam3              631 non-null    object
 27  main_cam_features      1268 non-null   object
 28  main_video             1239 non-null   object
 29  os                     1268 non-null   object
 30  software_updates       1228 non-null   object
 31  ai_features            780 non-null    object
 32  front_cam              1268 non-null   object
 33  front_cam_features     1026 non-null   object
 34  front_video            1229 non-null   object
 35  battery                1268 non-null   object
 36  charging               1268 non-null   object
 37  storage                1268 non-null   object
 38  ram                    1268 non-null   object
 39  sim                    1264 non-null   object
 40  tech                   1200 non-null   object
 41  2g                     1262 non-null   object
 42  3g                     1264 non-null   object
 43  4g                     1267 non-null   object
 44  5g                     1028 non-null   object
 45  speed                  1264 non-null   object
 46  wifi                   1268 non-null   object
 47  bluetooth              1266 non-null   object
 48  positioning_system     1268 non-null   object
 49  nfc                    595 non-null    object
 50  finger_print           1192 non-null   object
 51  sensors                1268 non-null   object
 52  add_features           469 non-null    object
 53  brand                  1268 non-null   category
 54  is_available           1268 non-null   int64
 55  is_flipkart_available  1268 non-null   int64
 56  is_amazon_available    1268 non-null   int64
 57  is_official_available  1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(8), object(45)
memory usage: 566.7+ KB

In [143]:
df['display_type'].sample(10)

585                   OLED, 120 Hz Refresh Rate, HDR10, 240 Hz Touch Sampling Rate
109                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
982                                               IPS LCD, 90 Hz Refresh Rate, SDR
217                       LCD, 90 Hz Refresh Rate, SDR, 120 Hz Touch Sampling Rate
1111               AMOLED, 120 Hz Refresh Rate, HDR10+, 480 Hz Touch Sampling Rate
912                                          Super AMOLED, 90 Hz Refresh Rate, SDR
657                   IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
881              Super AMOLED, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1245                                              IPS LCD, 60 Hz Refresh Rate, SDR
1072    Dynamic 2X AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [144]:
# creating column for display_panel_type

df['display_panel_type'] = df['display_type'].str.lower().str.split(',').str.get(0)

In [145]:
df['display_panel_type'].value_counts(dropna=False)

display_panel_type
amoled                          324
ips lcd                         310
super amoled                    105
lcd                              68
dynamic 2x amoled                60
super retina xdr oled            49
oled                             40
proxdr amoled                    32
p-oled                           30
pls lcd                          27
dot amoled                       25
hdr amoled                       23
e4 amoled                        17
dot ips lcd                      16
fluid amoled                     10
e5 amoled                         9
ultra smooth display ips lcd      9
super actua oled                  8
smooth display amoled             8
pro hdr amoled                    8
turbo amoled                      7
proxdr oled                       7
ultra amoled                      7
e6 amoled                         6
flow amoled                       6
q10+ amoled                       6
3d amoled amoled                  5
super retina xdr amoled           5
q10 amoled                        4
tft lcd                           4
hyperglow amoled                  3
e7 amoled                         3
fluid oled                        2
tft ips                           2
ips                               2
led                               2
u8 amoled                         2
ultra smooth display amoled       2
ultra smooth display lcd          2
trinity engine amoled             2
boundless display ips lcd         2
smooth display oled               1
true colour display amoled        1
dynamic ips lcd                   1
hdr oled                          1
super actua ips lcd               1
ips a-si                          1
smooth display ips lcd            1
smooth display lcd                1
dynamic amoled                    1
Name: count, dtype: int64

In [146]:
# there are more than 50+ category so we have to make new column

def display_panel_family(text):

    t = text.lower()

    if 'amoled' in t:
      return 'amoled'

    if 'oled' in t and 'amoled' not in t:
      return 'oled'

    if 'ips lcd' in t or ('ips' in t and 'tft' not in t):
      return 'ips lcd'

    if 'tft' in t:
      return 'tft'

    if 'led' in t:
      return 'led'

    if 'lcd' in t:
      return 'lcd'

    return 'unknown'

df['display_panel_family'] = df['display_panel_type'].apply(display_panel_family)

In [147]:
df['display_panel_family'].value_counts()

display_panel_family
amoled     681
ips lcd    343
oled       138
lcd         98
tft          6
led          2
Name: count, dtype: int64

In [148]:
# convert display_panel_family from object dtypes to category

df['display_panel_family'] = df['display_panel_family'].astype('category')

In [149]:
df['display_type'].sample(10)

1188                                                       AMOLED, 90 Hz Refresh Rate, HDR10+
75                                                             OLED, 120 Hz Refresh Rate, HDR
171                        AMOLED, 144 Hz Refresh Rate, LTPO, SDR, 360 Hz Touch Sampling Rate
433                          Q10 AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
753                        Super AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
27      Super Retina XDR AMOLED, 60 Hz Refresh Rate, Dolby Vision, 120 Hz Touch Sampling Rate
832                             IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
194                           AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
469                 3D AMOLED AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
1249                                                         IPS LCD, 60 Hz Refresh Rate, HDR
Name: display_type, dtype: object

In [150]:
# creating new col from display_type name display_hz

df['display_hz'] = df['display_type'].str.lower().str.split(',').str.get(1)

In [151]:
df['display_hz'] = df['display_hz'].str.split(' ').str.get(1)

In [152]:
df['display_hz'].value_counts()

display_hz
120    781
90     274
60     119
144     81
165     12
sdr      1
Name: count, dtype: int64

In [153]:
df[df['display_hz'].str.contains('sdr')]

,model_id,model,beebome_score,rating,rating_count,launch_on,old_price,price,launch_price,display_type,display_size,display_res,body_dimension,weight,body_front,body_back,body_side,build_quality,ports,ip_rating,speaker,chipset,cpu,gpu,main_cam,main_cam2,main_cam3,main_cam_features,main_video,os,software_updates,ai_features,front_cam,front_cam_features,front_video,battery,charging,storage,ram,sim,tech,2g,3g,4g,5g,speed,wifi,bluetooth,positioning_system,nfc,finger_print,sensors,add_features,brand,is_available,is_flipkart_available,is_amazon_available,is_official_available,display_panel_type,display_panel_family,display_hz
228,229,Moto E13 (8GB + 128GB),50,4.1,371000.0,2023-02-08,NaN,9299,6999,"IPS LCD, SDR","6.5 inches, 102 cm², 89.2% Screen To Body Ratio","HD+, 720 x 1600 pixels, 20:9 (269 ppi), 8-bit colours",164.19 x 74.95 x 8.47 mm,179.5 grams,Glass,Plastic,Plastic Frame,Plastic Material,"USB Type-C 2.0, 3.5mm Headphone Jack, OTG",IP52 (Dust and Splash Resistant),Mono Speaker,"Unisoc T606 (12 nm), 246197 Antutu Score",Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55),Mali-G57 MP1,"13 MP, f/2.2, (Wide-angle), 1.12 µm, PDAF",NaN,NaN,"HDR, LED Flash, Panorama, Pro Mode",1080p@30fps,"Android Go 13, Motorola MyUx",NaN,"AI Beauty, AI Camera, Auto Smile Capture","5 MP, f/2.2, (Wide-angle), 1.12 µm, 1/5""","AI Beauty Mode, HDR Photos, Portrait Mode",1080p@30fps,"5000 mAh, Lithium Polymer (Non-removable)",10W (wired),"128GB, eMMC 5.1","8GB, LPDDR4X",Hybrid Dual SIM (2 Nano SIMs + 1 microSD),"GSM, HSPA, LTE","3, 5, 8 (3 bands)","1, 5, 8 (3 bands)","1, 3, 5, 7, 8, 20, 28, 38, 40, 41 (10 bands)",NaN,"GSM, HSPA, LTE","Wi-Fi 5 802.11 a/b/g/n/ac, Hotspot, Dual Band","A2DP, AAC, LE, SBC","A-GPS, GALILEO, GLONASS, GPS, LTEPP, SUPL",NaN,NaN,"Accelerometer, Ambient Light Sensor, Proximity Sensor",NaN,motorola,0,0,1,0,ips lcd,ips lcd,sdr

In [154]:
# this model display_hz is not available so fill 60 as default
df.loc[228,'display_hz'] = 60

In [155]:
df['display_hz'].value_counts()

display_hz
120    781
90     274
60     119
144     81
165     12
60       1
Name: count, dtype: int64

In [156]:
# converting data types of diplay_hz to numeric

df['display_hz'] = pd.to_numeric(df['display_hz'],errors='coerce')

In [157]:
df['display_hz'].dtypes

dtype('int64')

In [158]:
df['display_type'].sample(20)

559                                                           IPS LCD, 120 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
212                                                        AMOLED, 120 Hz Refresh Rate, HDR10+, 1200 Hz Touch Sampling Rate
72                                                                         Super Actua OLED, 120 Hz Refresh Rate, LTPO, HDR
555                                                                                     AMOLED, 120 Hz Refresh Rate, HDR10+
352                                                                     HDR AMOLED, 165 Hz Refresh Rate, LTPO, Dolby Vision
8       Super Retina XDR OLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 360 Hz Touch Sampling Rate, Anti Reflection Coating
937                                                                               Super AMOLED, 120 Hz Refresh Rate, HDR10+
790                                                                                        TFT IPS, 60 Hz Refresh Rate, SDR
973                                                                                        PLS LCD, 60 Hz Refresh Rate, SDR
15                                                                         Super Retina XDR OLED, 60 Hz Refresh Rate, HDR10
1227                                                              LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
315                                                  AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 1000 Hz Touch Sampling Rate
848                                                                                  Super AMOLED, 120 Hz Refresh Rate, SDR
594                                                              OLED, 120 Hz Refresh Rate, HDR, 240 Hz Touch Sampling Rate
622                                      Ultra Smooth Display IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
1136                                                                              Super AMOLED, 120 Hz Refresh Rate, HDR10+
548                                                            Flow AMOLED, 120 Hz Refresh Rate, 240 Hz Touch Sampling Rate
453                                                            AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
974                                                                                        IPS LCD, 90 Hz Refresh Rate, SDR
1080                                                          IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [159]:
# keeping only hdr10+ , hd10 and sdr
def display_dynamic_range(text):

  t = text

  if 'Dolby Vision' in t:
    return 'Dolby Vision'
  if 'HDR10+' in t:
    return 'HDR10+'
  if 'ProXDR' in t:
    return 'ProXDR'
  if 'HDR' in t:
    return 'HDR'
  if 'HDR10' in t:
    return 'HDR10'
  if 'Pro HDR' in t:
    return 'HDR'

  return 'SDR'

df['display_dynamic_range'] = df['display_type'].apply(display_dynamic_range)

In [160]:
df['display_dynamic_range'].value_counts(dropna=False)

display_dynamic_range
SDR             660
HDR10+          371
Dolby Vision    138
HDR              87
ProXDR           12
Name: count, dtype: int64

In [161]:
df['display_dynamic_range'].count()

np.int64(1268)

In [162]:
df[df['display_dynamic_range'].str.contains('SDR')]['display_type'].sample(20)

877                                          LCD, 60 Hz Refresh Rate, SDR
928                                Super AMOLED, 120 Hz Refresh Rate, SDR
1201                                         LCD, 90 Hz Refresh Rate, SDR
654         IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
732            OLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
242         IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
128          AMOLED, 120 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
746          IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
898                                      IPS LCD, 90 Hz Refresh Rate, SDR
236          IPS LCD, 90 Hz Refresh Rate, SDR, 120 Hz Touch Sampling Rate
1076        IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
234                                      IPS LCD, 90 Hz Refresh Rate, SDR
233                                      IPS LCD, 90 Hz Refresh Rate, SDR
256         IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
738         IPS LCD, 144 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
137                                      IPS LCD, 60 Hz Refresh Rate, SDR
961                                Super AMOLED, 120 Hz Refresh Rate, SDR
500         IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
1073    Turbo AMOLED, 60 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
901                                      PLS LCD, 90 Hz Refresh Rate, SDR
Name: display_type, dtype: object

In [163]:
# converting display_dynamic_range into category
df['display_dynamic_range'] = df['display_dynamic_range'].astype('category')

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 62 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model_id               1268 non-null   int64
 1   model                  1268 non-null   object
 2   beebome_score          1268 non-null   int64
 3   rating                 1268 non-null   float64
 4   rating_count           994 non-null    float64
 5   launch_on              1268 non-null   datetime64[ns]
 6   old_price              844 non-null    float64
 7   price                  1268 non-null   int64
 8   launch_price           1268 non-null   int64
 9   display_type           1268 non-null   object
 10  display_size           1268 non-null   object
 11  display_res            1268 non-null   object
 12  body_dimension         1268 non-null   object
 13  weight                 1268 non-null   object
 14  body_front             1268 non-null   object
 15  body_back              1238 non-null   object
 16  body_side              1251 non-null   object
 17  build_quality          739 non-null    object
 18  ports                  1268 non-null   object
 19  ip_rating              915 non-null    object
 20  speaker                1265 non-null   object
 21  chipset                1268 non-null   object
 22  cpu                    1268 non-null   object
 23  gpu                    1250 non-null   object
 24  main_cam               1268 non-null   object
 25  main_cam2              1214 non-null   object
 26  main_cam3              631 non-null    object
 27  main_cam_features      1268 non-null   object
 28  main_video             1239 non-null   object
 29  os                     1268 non-null   object
 30  software_updates       1228 non-null   object
 31  ai_features            780 non-null    object
 32  front_cam              1268 non-null   object
 33  front_cam_features     1026 non-null   object
 34  front_video            1229 non-null   object
 35  battery                1268 non-null   object
 36  charging               1268 non-null   object
 37  storage                1268 non-null   object
 38  ram                    1268 non-null   object
 39  sim                    1264 non-null   object
 40  tech                   1200 non-null   object
 41  2g                     1262 non-null   object
 42  3g                     1264 non-null   object
 43  4g                     1267 non-null   object
 44  5g                     1028 non-null   object
 45  speed                  1264 non-null   object
 46  wifi                   1268 non-null   object
 47  bluetooth              1266 non-null   object
 48  positioning_system     1268 non-null   object
 49  nfc                    595 non-null    object
 50  finger_print           1192 non-null   object
 51  sensors                1268 non-null   object
 52  add_features           469 non-null    object
 53  brand                  1268 non-null   category
 54  is_available           1268 non-null   int64
 55  is_flipkart_available  1268 non-null   int64
 56  is_amazon_available    1268 non-null   int64
 57  is_official_available  1268 non-null   int64
 58  display_panel_type     1268 non-null   object
 59  display_panel_family   1268 non-null   category
 60  display_hz             1268 non-null   int64
 61  display_dynamic_range  1268 non-null   category
dtypes: category(3), datetime64[ns](1), float64(3), int64(9), object(46)
memory usage: 589.4+ KB

In [165]:
df[df['display_type'].str.contains("Touch Sampling Rate")]['display_type'].sample(20)

690                                                     E4 AMOLED, 120 Hz Refresh Rate, HDR10+, 1000 Hz Touch Sampling Rate
321                                                  AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 1000 Hz Touch Sampling Rate
515                                                         Dot AMOLED, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1203                                                               LED, 90 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
824                                                            IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1044              Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate, Anti Reflection Coating
445                                                                LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
534                                                         AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
386                                                             IPS LCD, 90 Hz Refresh Rate, SDR, 90 Hz Touch Sampling Rate
985                                                       Super AMOLED, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1035              Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate, Anti Reflection Coating
681                                          E6 AMOLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 240 Hz Touch Sampling Rate
456                                                               LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
1171                               AMOLED, 120 Hz Refresh Rate, HDR10+, 120 Hz Touch Sampling Rate, Anti Reflection Coating
34      Super Retina XDR OLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 240 Hz Touch Sampling Rate, Anti Reflection Coating
1251                                                           AMOLED, 120 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
586                                                            OLED, 120 Hz Refresh Rate, HDR10, 240 Hz Touch Sampling Rate
712                                                         AMOLED, 120 Hz Refresh Rate, HDR10+, 360 Hz Touch Sampling Rate
842                                                        Dot AMOLED, 120 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
147                                                          AMOLED, 144 Hz Refresh Rate, HDR10, 360 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [166]:
# using regx to extract touch sampling rate

def extract_touch_sampling_rate(text):

  t = text.lower()

  match = re.search(r'(\d{2,4})\s*hz\s*touch', t)

  if match:
    return int(match.group(1))

  return np.nan

df['touch_sampling_rate'] = df['display_type'].apply(extract_touch_sampling_rate)

In [167]:
df['touch_sampling_rate'].value_counts(dropna=False)

touch_sampling_rate
NaN       416
240.0     369
180.0     164
360.0     121
120.0      47
300.0      40
1000.0     29
480.0      27
1200.0     13
90.0       10
720.0       5
288.0       5
60.0        4
270.0       3
2000.0      3
1500.0      3
960.0       2
2200.0      2
600.0       2
2500.0      2
3000.0      1
Name: count, dtype: int64

In [168]:
df['display_type'].sample(20)

259                                                                              AMOLED, 120 Hz Refresh Rate, SDR
464                                         AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate
717                                                 AMOLED, 120 Hz Refresh Rate, SDR, 2200 Hz Touch Sampling Rate
39                                  Super Retina XDR OLED, 60 Hz Refresh Rate, HDR10+, 180 Hz Touch Sampling Rate
1190                                                  AMOLED, 90 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
499                                                 IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
677                                            AMOLED, 120 Hz Refresh Rate, LTPO, HDR, 360 Hz Touch Sampling Rate
1158                                              AMOLED, 120 Hz Refresh Rate, HDR10+, 300 Hz Touch Sampling Rate
905                                                                              IPS LCD, 90 Hz Refresh Rate, SDR
950                                             Super AMOLED, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1026    Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate, Anti Reflection Coating
40                                  Super Retina XDR OLED, 60 Hz Refresh Rate, HDR10+, 180 Hz Touch Sampling Rate
907                                              Super AMOLED, 90 Hz Refresh Rate, SDR, 90 Hz Touch Sampling Rate
182                                            AMOLED, 144 Hz Refresh Rate, LTPO, SDR, 360 Hz Touch Sampling Rate
627                                                  IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1189                                                  AMOLED, 90 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
445                                                      LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1068                                                   Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, Dolby Vision
682                                E6 AMOLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 240 Hz Touch Sampling Rate
887                                                                             TFT LCD, 120 Hz Refresh Rate, SDR
Name: display_type, dtype: object

In [169]:
df[df['display_type'].str.contains('LTPO')]['display_type'].count()

np.int64(212)

In [170]:
def extract_lpo(text):

  t = text.lower()

  if 'ltpo' in t:
    return 1

  return 0

df['has_ltpo'] = df['display_type'].apply(extract_lpo)

In [171]:
df['has_ltpo'].value_counts()

has_ltpo
0    1056
1     212
Name: count, dtype: int64

In [172]:
df[df['display_type'].str.contains('Anti Reflection Coating')]['display_type'].count()

np.int64(77)

In [173]:
def extract_anti_reflecting_coating(text):

  t = text.lower()

  if 'anti reflection coating' in t:
    return 1

  return 0

df['has_anti_reflection_coating'] = df['display_type'].apply(extract_anti_reflecting_coating)

In [174]:
df['has_anti_reflection_coating'].value_counts()

has_anti_reflection_coating
0    1191
1      77
Name: count, dtype: int64

In [175]:
df['display_type'].sample(20)

267                                 p-OLED, 144 Hz Refresh Rate, HDR10+, 360 Hz Touch Sampling Rate
462                           AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate
2                                           Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision
624                               Super AMOLED, 90 Hz Refresh Rate, SDR, 360 Hz Touch Sampling Rate
312                                 AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
1159                                                            AMOLED, 120 Hz Refresh Rate, HDR10+
823                                    IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
177     E4 AMOLED, 120 Hz Refresh Rate, HDR10+, 360 Hz Touch Sampling Rate, Anti Reflection Coating
493                                                            Dot IPS LCD, 90 Hz Refresh Rate, SDR
635                                    IPS LCD, 60 Hz Refresh Rate, SDR, 120 Hz Touch Sampling Rate
30                                          Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision
1192                                                               IPS LCD, 60 Hz Refresh Rate, SDR
152                              AMOLED, 120 Hz Refresh Rate, LTPO, SDR, 180 Hz Touch Sampling Rate
543                      Flow AMOLED, 120 Hz Refresh Rate, Dolby Vision, 240 Hz Touch Sampling Rate
763                             ProXDR AMOLED, 120 Hz Refresh Rate, HDR, 180 Hz Touch Sampling Rate
136                                                                IPS LCD, 60 Hz Refresh Rate, SDR
1060                     Dynamic 2X AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
319                                AMOLED, 120 Hz Refresh Rate, HDR10+, 1000 Hz Touch Sampling Rate
537                                Dot AMOLED, 120 Hz Refresh Rate, HDR, 360 Hz Touch Sampling Rate
477                                 AMOLED, 90 Hz Refresh Rate, HDR10+, 1000 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 65 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
dtypes: category(3), datetime64[ns](1), float64(4), int64(11), object(46)
memory usage: 619.1+ KB

In [177]:
df['display_size'].sample(20)

687                        6.79 inches, 112.8 cm², 94.2% Screen To Body Ratio
562                                        6.7 inches Curved Display, 108 cm²
400                          6.72 inches, 109 cm², 91.4% Screen To Body Ratio
170                          6.78 inches, 111 cm², 90.4% Screen To Body Ratio
832                                                    6.88 inches, 112.4 cm²
657                          6.75 inches, 110 cm², 90.3% Screen To Body Ratio
566                          6.72 inches, 109 cm², 91.4% Screen To Body Ratio
17                            6.7 inches, 110.2 cm², 88% Screen To Body Ratio
88      6.7 inches Quad Curved Display, 108.9 cm², 93.3% Screen To Body Ratio
0                              6.1 inches, 90.2 cm², 86% Screen To Body Ratio
209                        6.38 inches, 98.3 cm², 84.14% Screen To Body Ratio
852                                                    6.67 inches, 107.4 cm²
666                       6.67 inches, 107.2 cm², 89.97% Screen To Body Ratio
485                          6.52 inches, 102.6 cm², 81% Screen To Body Ratio
580                          6.72 inches, 109 cm², 91.4% Screen To Body Ratio
2                           6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio
1081                       6.58 inches, 104.3 cm², 90.6% Screen To Body Ratio
1099          6.78 inches Curved Display, 111 cm², 90.2% Screen To Body Ratio
1119                                                              6.72 inches
426                           6.7 inches, 108 cm², 93.7% Screen To Body Ratio
Name: display_size, dtype: object

In [178]:
# make new col display_inches

df['display_inches'] = df['display_size'].str.split(' ').str.get(0)

In [179]:
df['display_inches'].value_counts()

display_inches
6.7      185
6.67     168
6.78     122
6.5       77
6.6       71
6.77      59
6.72      58
6.74      54
6.56      44
6.8       36
6.58      30
6.1       27
6.9       27
6.4       22
6.83      21
6.43      20
6.44      17
6.59      17
6.88      15
6.71      14
6.3       14
6.79      14
6.52      12
6.82      11
6.62      11
6.55      11
6.57       9
6.73       9
6.38       9
6.65       8
6.2        8
6.51       8
7.6        7
6.75       7
6.68       7
6.31       5
8          4
6.69       4
6.66       4
6.85       4
6.53       3
8.03       3
6.36       2
6.745      2
6.32       2
7.82       2
164.4      1
7          1
6.15       1
6.64       1
Name: count, dtype: int64

In [180]:
df[df['display_inches'] == '164.4'] # given in mm not inches

,model_id,model,beebome_score,rating,rating_count,launch_on,old_price,price,launch_price,display_type,display_size,display_res,body_dimension,weight,body_front,body_back,body_side,build_quality,ports,ip_rating,speaker,chipset,cpu,gpu,main_cam,main_cam2,main_cam3,main_cam_features,main_video,os,software_updates,ai_features,front_cam,front_cam_features,front_video,battery,charging,storage,ram,sim,tech,2g,3g,4g,5g,speed,wifi,bluetooth,positioning_system,nfc,finger_print,sensors,add_features,brand,is_available,is_flipkart_available,is_amazon_available,is_official_available,display_panel_type,display_panel_family,display_hz,display_dynamic_range,touch_sampling_rate,has_ltpo,has_anti_reflection_coating,display_inches
119,120,Infinix Note 12 Pro,27,4.2,71000.0,2022-08-26,NaN,16999,16999,"AMOLED, 60 Hz Refresh Rate, LTPO, SDR","164.4 inches, 76.5 cm²","FHD+, 1080 x 2400 pixels, 20:9 (393 ppi), 8-bit 16.7 Million Colours, 1000 nits(Peak Brightness)",164.4 x 76.5 x 7.8 mm,192 grams,Glass,Plastic,Plastic Frame,Plastic Material,"USB Type-C 2.0, 3.5mm Headphone Jack",NaN,Stereo Speakers,"MediaTek Helio G99 (6 nm), 422909 Antutu Score",Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55),Mali-G57 MC2,"108 MP, f/1.8, (Wide-angle), 0.8 µm, 1/1.67"", Auto Focus","2 MP, f/2.4, (Depth), 0.64 µm","f/2.4, (QVGA), 0.56 µm","HDR, Panorama, Quad-LED Flash","1440p@30fps, 1080p@60fps","Android 12, XOS",1 year(s) of Software updates and 2 year(s) of Security updates,NaN,"16 MP, f/2.0, 0.8 µm",NaN,1440p@30fps,"5000 mAh, Lithium Polymer (Non-removable)",33W (wired),"256GB, UFS 2.2","8GB, LPDDR4X","Dual SIM (nano-SIM, dual stand-by)","GSM, HSPA, LTE","2, 3, 5, 8 (4 bands)","1, 2, 4, 5, 8 (5 bands)","1, 2, 3, 4, 5, 7, 8, 20, 28A, 28B, 38, 40, 41 (13 bands)",NaN,"GSM, HSPA, LTE","Wi-Fi 5 802.11 a/b/g/n/ac, Hotspot, Wi-Fi Direct, Dual Band","5, A2DP, AAC, LE, SBC",GPS,NaN,Side Mounted,"Accelerometer, Compass, G-Sensor, Gyroscope, Light Sensor, Proximity Sensor",NaN,infinix,0,1,1,0,amoled,amoled,60,SDR,NaN,1,0,164.4

In [181]:
# fill with correct value
df.loc[119,'display_inches'] = 6.7

In [182]:
df['display_inches'].value_counts()

display_inches
6.7      185
6.67     168
6.78     122
6.5       77
6.6       71
6.77      59
6.72      58
6.74      54
6.56      44
6.8       36
6.58      30
6.1       27
6.9       27
6.4       22
6.83      21
6.43      20
6.44      17
6.59      17
6.88      15
6.71      14
6.3       14
6.79      14
6.52      12
6.82      11
6.62      11
6.55      11
6.57       9
6.73       9
6.38       9
6.65       8
6.2        8
6.51       8
7.6        7
6.75       7
6.68       7
6.31       5
8          4
6.69       4
6.66       4
6.85       4
6.53       3
8.03       3
6.36       2
6.745      2
6.32       2
7.82       2
6.7        1
7          1
6.15       1
6.64       1
Name: count, dtype: int64

In [184]:
df['display_inches'].count()

np.int64(1268)

In [186]:
# convert dtypes of display_inches to float

df['display_inches'] = pd.to_numeric(df['display_inches'])

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 66 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
dtypes: category(3), datetime64[ns](1), float64(5), int64(11), object(46)
memory usage: 629.0+ KB

In [188]:
df['display_size'].sample(20)

166                                                6.62 inches, 105.8 cm²
735                        6.57 inches, 105 cm², 93% Screen To Body Ratio
924                     6.6 inches, 106.9 cm², 84.9% Screen To Body Ratio
634                       6.5 inches, 102 cm², 88.7% Screen To Body Ratio
1173                    6.31 inches, 97.6 cm², 90.2% Screen To Body Ratio
400                      6.72 inches, 109 cm², 91.4% Screen To Body Ratio
300                                                   6.5 inches, 102 cm²
744                    6.74 inches, 109.7 cm², 90.3% Screen To Body Ratio
654                   6.67 inches, 107.2 cm², 89.97% Screen To Body Ratio
598     6.83 inches Curved Display, 113.3 cm², 93.8% Screen To Body Ratio
798                                                6.79 inches, 109.5 cm²
7                          6.1 inches, 91.7 cm², 87% Screen To Body Ratio
1115                           6.77 inches Quad Curved Display, 110.9 cm²
946                     6.6 inches, 104.9 cm², 82.5% Screen To Body Ratio
1228                   6.68 inches, 107.4 cm², 85.1% Screen To Body Ratio
218                    6.56 inches, 103.4 cm², 83.6% Screen To Body Ratio
1122                     6.44 inches, 100.1 cm², 88% Screen To Body Ratio
114                     6.7 inches, 108.4 cm², 90.2% Screen To Body Ratio
437          6.8 inches Flip Display, 108 cm², 85.9% Screen To Body Ratio
248                     6.6 inches, 103.6 cm², 91.4% Screen To Body Ratio
Name: display_size, dtype: object

In [196]:
def extract_body_ratio(text):

  t = text.lower()

  if '%' in t:
    return t

  return np.nan

df['display_body_ratio'] = df['display_size'].apply(extract_body_ratio)

In [211]:
df['display_body_ratio'].count()

np.int64(1036)

In [212]:
df['display_body_ratio'] = df['display_body_ratio'].str.split('%').str.get(0).str.split(',').str.get(-1)

In [214]:
df['display_body_ratio'].value_counts(dropna=False)

display_body_ratio
NaN       232
 93        40
 91.4      36
 90.8      35
 83.6      28
         ...
 86.48      1
 93.2       1
 90.04      1
 82.9       1
 94.85      1
Name: count, Length: 154, dtype: int64

In [215]:
# convert dtypes to floar
df['display_body_ratio'] = pd.to_numeric(df['display_body_ratio'])

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 67 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
dtypes: category(3), datetime64[ns](1), float64(6), int64(11), object(46)
memory usage: 638.9+ KB

In [250]:
df['display_size'].sample(20)

960                                                                           6.5 inches, 103.7 cm²
1250                                             6.67 inches, 107.4 cm², 86.1% Screen To Body Ratio
397                                              6.67 inches, 107.2 cm², 89.9% Screen To Body Ratio
877                                                                           6.6 inches, 104.9 cm²
1060    7.6 inches Foldable Display, 183.2 cm², 90.9% Screen To Body Ratio, 6.2 inches rear display
709                                                 6.5 inches, 102 cm², 88.7% Screen To Body Ratio
1231                                             6.67 inches, 107.4 cm², 91.9% Screen To Body Ratio
918                                                   6.5 inches, 101 cm², 84% Screen To Body Ratio
933                                               6.6 inches, 106.9 cm², 85.8% Screen To Body Ratio
671                               6.78 inches Curved Display, 111.7 cm², 94.2% Screen To Body Ratio
1226                                             6.68 inches, 107.4 cm², 85.1% Screen To Body Ratio
1179                                               6.31 inches, 98 cm², 94.66% Screen To Body Ratio
504                                                                          6.67 inches, 107.4 cm²
1195                                                                         6.56 inches, 103.4 cm²
211                                                             6.78 inches Curved Display, 111 cm²
385                                              6.56 inches, 103.4 cm², 83.3% Screen To Body Ratio
914                                                 6.7 inches, 110.2 cm², 86% Screen To Body Ratio
1197                                             6.56 inches, 103.4 cm², 83.6% Screen To Body Ratio
744                                              6.74 inches, 109.7 cm², 90.3% Screen To Body Ratio
361                                              6.74 inches, 109.7 cm², 93.5% Screen To Body Ratio
Name: display_size, dtype: object

In [240]:
df[df['display_size'].str.contains('Curved')]['display_size'].count()

np.int64(263)

In [241]:
df[df['display_size'].str.contains('Foldable|Flip')]['display_size'].count()

np.int64(35)

In [242]:
def extract_curved(text):

  if 'Curved' in text:
    return 1
  return 0

df['has_curved'] = df['display_size'].apply(extract_curved)

In [243]:
df['has_curved'].value_counts()

has_curved
0    1005
1     263
Name: count, dtype: int64

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 68 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
dtypes: category(3), datetime64[ns](1), float64(6), int64(12), object(46)
memory usage: 648.8+ KB

In [245]:
def extract_foldable(text):

  if 'Foldable' in text or 'Flip' in text:
    return 1

  return 0

df['has_foldable'] = df['display_size'].apply(extract_foldable)

In [246]:
df['has_foldable'].value_counts()

has_foldable
0    1233
1      35
Name: count, dtype: int64

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 69 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
 68  has_foldable                 1268 non-null   int64
dtypes: category(3), datetime64[ns](1), float64(6), int64(13), object(46)
memory usage: 658.8+ KB

In [256]:
df['display_res'].sample(20)

1023                                                                            QHD+, 1440 x  3088 pixels, 19.3:9 (500 ppi), 10-bit 16 Million Colours, 1750 nits(Peak Brightness), 1200 nits(High Brightness)
889                                                                                           HD+, 720 x  1600 pixels, 20:9 (270 ppi), 8-bit 16 Million Colours, 400 nits(Peak Brightness), Eye Comfort Shield
1083                                                                                                                                        FHD+, 1080 x  2408 pixels, 20:9 (401 ppi), 8-bit colours, 96% NTSC
914                                                                               FHD+, 1080 x  2340 pixels, 19.5:9 (385 ppi), 8-bit 16 Million Colours, 1100 nits(Peak Brightness), 800 nits(High Brightness)
1175                                                                       FHD+, 1260 x  2800 pixels, 20:9 (460 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 4500 nits(Peak Brightness), Blue Light Filters
847                 FHD+, 1080 x  2400 pixels, 20:9 (409 ppi), 8-bit 16.7 Million Colours, 100% DCI-P3, 1000 nits(Peak Brightness), 700 nits(Typical Brightness), Eye Comfort Shield, 4500000:1 Contrast Ratio
1237                                                                                                                                        FHD+, 1080 x  2408 pixels, 20:9 (401 ppi), 8-bit colours, 96% NTSC
1223                                                                                            HD+, 720 x  1612 pixels, 20:9 (269 ppi), 8-bit colours, 840 nits(High Brightness), TUV Rheinland certification
81                             FHD, 1080 x  2424 pixels, 20:9 (422 ppi), 10-bit 16 Million Colours, 100% DCI-P3, 2700 nits(Peak Brightness), 1800 nits(High Brightness), PWM Dimming, 2000000:1 Contrast Ratio
298                                                                                      HD+, 720 x  1612 pixels, 20:9 (269 ppi), 8-bit colours, 100% DCI-P3, 537 nits(Peak Brightness), 1000:1 Contrast Ratio
1253                                                                 FHD+, 1080 x  2400 pixels, 20:9 (395 ppi), 8-bit colours, 1200 nits(Peak Brightness), SGS Display Certification, 4500000:1 Contrast Ratio
716           FHD+, 1080 x  2400 pixels, 20:9 (395 ppi), 10-bit colours, 106% NTSC, 1200 nits(Peak Brightness), 600 nits(High Brightness), 600 nits(Typical Brightness), PWM Dimming, 5000000:1 Contrast Ratio
491                                                                                       HD+, 720 x  1650 pixels, 20:9 (268 ppi), 8-bit colours, 500 nits(High Brightness), DC Dimming, 1500:1 Contrast Ratio
1116                                         FHD+, 1080 x  2392 pixels, 19.9:9 (387 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 1800 nits(Peak Brightness), 1300 nits(High Brightness), Blue Light Filters
1036                                                    QHD+, 1440 x  3120 pixels, 19.3:9 (501 ppi), 10-bit 16 Million Colours, 100% DCI-P3, 2600 nits(Peak Brightness), PWM Dimming, 5000000:1 Contrast Ratio
3                                                   FHD+, 1284 x  2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio
51      1.5K, 1260 x  2736 pixels, 19.5:9 (460 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 3000 nits(Peak Brightness), 1600 nits(High Brightness), 1000 nits(Typical Brightness), 2000000:1 Contrast Ratio
338               QHD+, 1440 x  3168 pixels, 19.8:9 (510 ppi), 10-bit 1 Billion Colours, 100% DCI-P3, 4500 nits(Peak Brightness), 1600 nits(High Brightness), 600 nits(Typical Brightness), Blue Light Filters
789                                                                                       HD+, 720 x  1650 pixels, 20.6:9 (268 ppi), 8-bit colours, 70% NTSC, 400 nits(Peak Brightness), 1500:1 Contrast Ratio
817                                                                                      HD+, 720 x  1600 pixels, 20:9 (269 ppi), 8-bit colours, 70% NTSC, 400 nits(Typical Brightness), 1500:1 Contrast Ratio
Name: display_res, dtype: object

In [261]:
df['res_category'] = df['display_res'].str.split(',').str.get(0)

In [262]:
df['res_category'].value_counts()

res_category
FHD+                   742
HD+                    249
1.5K                   180
QHD+                    50
HD                      16
FHD                      9
WQHD+                    6
2K                       6
QXGA+                    6
1080 x  2520 pixels      2
QHD                      1
2.5K                     1
Name: count, dtype: int64

In [264]:
df[df['res_category'].str.contains('pixels')][['model','display_res']]

,model,display_res
1055,Samsung Galaxy Z Flip 7 (12GB + 512GB),"1080 x 2520 pixels, 21:9 (397 ppi), 12-bit 16 Million Colours, 2600 nits(High Brightness)"
1058,Samsung Galaxy Z Flip 7,"1080 x 2520 pixels, 21:9 (397 ppi), 12-bit 16 Million Colours, 2600 nits(High Brightness)"

In [265]:
df.loc[[1055,1058],'res_category'] = 'FHD+'

In [266]:
df['res_category'].value_counts()

res_category
FHD+     744
HD+      249
1.5K     180
QHD+      50
HD        16
FHD        9
2K         6
QXGA+      6
WQHD+      6
QHD        1
2.5K       1
Name: count, dtype: int64

In [275]:
df['res_category'] = df['res_category'].replace('QXGA+','QHD+')
df['res_category'] = df['res_category'].replace('WQHD+','QHD+')
df['res_category'] = df['res_category'].replace('QHD','QHD+')
df['res_category'] = df['res_category'].replace('2K','1.5K')
df['res_category'] = df['res_category'].replace('2.5K','1.5K')

In [276]:
df['res_category'].value_counts()

res_category
FHD+    744
HD+     249
1.5K    187
QHD+     63
HD       16
FHD       9
Name: count, dtype: int64

In [278]:
df['res_category'] = df['res_category'].astype('category')

In [279]:
df['res_category'].value_counts()

res_category
FHD+    744
HD+     249
1.5K    187
QHD+     63
HD       16
FHD       9
Name: count, dtype: int64

In [280]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 70 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
 68  has_foldable                 1268 non-null   int64
 69  res_category                 1268 non-null   category
dtypes: category(4), datetime64[ns](1), float64(6), int64(13), object(46)
memory usage: 660.2+ KB

In [281]:
df['display_res'].sample(20)

964                                                                            FHD+, 1080 x  2400 pixels, 20:9 (393 ppi), 8-bit 16 Million Colours, 800 nits(High Brightness), Eye Comfort Shield
682     1.5K, 1264 x  2780 pixels, 20:9 (450 ppi), 10-bit 1.07 Billion Colours, 120% DCI-P3, 6500 nits(Peak Brightness), 2000 nits(High Brightness), Blue Light Filters, 6000000:1 Contrast Ratio
142                                                                                                             HD+, 720 x  1612 pixels, 20:9 (267 ppi), 8-bit colours, 500 nits(Peak Brightness)
763                         FHD+, 1080 x  2400 pixels, 20:9 (395 ppi), 8-bit colours, 85% DCI-P3, 2000 nits(Peak Brightness), 600 nits(Typical Brightness), PWM Dimming, 2000000:1 Contrast Ratio
638                                                                  HD+, 720 x  1600 pixels, 20:9 (270 ppi), 8-bit 16.7 Million Colours, 400 nits(Peak Brightness), 400 nits(Typical Brightness)
110                                                                       FHD+, 1080 x  2460 pixels, 20:9 (396 ppi), 8-bit 16.7 Million Colours, 580 nits(Peak Brightness), 1500:1 Contrast Ratio
419                                      FHD+, 1080 x  2412 pixels, 20:9 (394 ppi), 10-bit 1 Billion Colours, 1100 nits(Peak Brightness), 900 nits(High Brightness), 500 nits(Typical Brightness)
261                                                           1.5K, 1220 x  2712 pixels, 20:9 (446 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 4500 nits(Peak Brightness), Blue Light Filters
1072                                                         FHD+, 1080 x  2340 pixels, 19.5:9 (403 ppi), 8-bit 16.7 Million Colours, 100% DCI-P3, 1200 nits(Peak Brightness), Eye Comfort Shield
558                                                                                                                                      FHD+, 1080 x  2400 pixels, 20:9 (392 ppi), 8-bit colours
768                                                               1.5K, 1272 x  2800 pixels, 19.5:9 (390 ppi), 8-bit colours, 100% DCI-P3, 1500 nits(Peak Brightness), 1200 nits(High Brightness)
144                                                                                                             HD+, 720 x  1612 pixels, 20:9 (267 ppi), 8-bit colours, 500 nits(Peak Brightness)
493                                                                  HD+, 720 x  1600 pixels, 20:9 (260 ppi), 8-bit 16.7 Million Colours, 600 nits(High Brightness), 450 nits(Typical Brightness)
1154                                FHD+, 1080 x  2392 pixels, 20:9 (387 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 4500 nits(Peak Brightness), Blue Light Filters, 8000000:1 Contrast Ratio
93                             FHD+, 1080 x  2400 pixels, 20:9 (395 ppi), 10-bit 1 Billion Colours, 100% DCI-P3, 900 nits(Peak Brightness), TUV Rheinland certification, 5000000:1 Contrast Ratio
1248                                                                                                                                     FHD+, 1080 x  2408 pixels, 20:9 (409 ppi), 8-bit colours
86                                                FHD+, 1200 x  2664 pixels, 19.98:9 (435 ppi), 10-bit 1.07 Billion Colours, 100% DCI-P3, 4000 nits(High Brightness), TUV Rheinland certification
187                                                                                                   FHD+, 1080 x  2392 pixels, (388 ppi), 8-bit colours, 60% DCI-P3, 5000 nits(Peak Brightness)
1092                                              FHD+, 1080 x  2400 pixels, 20:9 (394 ppi), 8-bit colours, 100% DCI-P3, 1800 nits(Peak Brightness), Blue Light Filters, 8000000:1 Contrast Ratio
640                                    FHD, 1080 x  2408 pixels, 20:9 (401 ppi), 8-bit 16.7 Million Colours, 600 nits(High Brightness), 480 nits(Typical Brightness), TUV Rheinland certification
Name: display_res, dtype: object

In [293]:
df['display_pixels'] = df['display_res'].str.split(',').str.get(1)

In [294]:
df['display_pixels'].value_counts()

display_pixels
1080 x  2400 pixels    307
720 x  1600 pixels     128
1080 x  2340 pixels     92
1080 x  2412 pixels     79
1080 x  2408 pixels     75
                      ...
2152 x  2076 pixels      1
2076 x  2152 pixels      1
1224 x  2912 pixels      1
1080 x  2373 pixels      1
1080 x  2388 pixels      1
Name: count, Length: 70, dtype: int64

In [296]:
df[~df['display_pixels'].str.contains('pixels')][['model','display_res','display_pixels']]

,model,display_res,display_pixels
1055,Samsung Galaxy Z Flip 7 (12GB + 512GB),"1080 x 2520 pixels, 21:9 (397 ppi), 12-bit 16 Million Colours, 2600 nits(High Brightness)",21:9 (397 ppi)
1058,Samsung Galaxy Z Flip 7,"1080 x 2520 pixels, 21:9 (397 ppi), 12-bit 16 Million Colours, 2600 nits(High Brightness)",21:9 (397 ppi)

In [298]:
df.loc[[1055,1058],'display_pixels'] = '1080 x 2520 pixels'

In [301]:
df[df['display_pixels'].str.contains('pixels')]['display_pixels'].count()

np.int64(1268)

In [304]:
df['res_width'] = df['display_pixels'].str.split('x').str.get(0)

In [305]:
df['res_width'].value_counts()

res_width
 1080     676
 720      267
 1260      47
 1440      44
 1220      38
 1280      24
 1272      22
 1264      19
 1179      14
 1290      13
 1256      10
 1240       9
 1206       8
 1216       7
 1224       7
 1320       7
 1200       7
 1084       7
 1170       6
 1344       5
 1812       4
 1968       3
 1856       3
 1284       3
 2400       3
 1088       3
 2200       2
1080        2
 2268       2
 1400       2
 1236       2
 2152       1
 2076       1
Name: count, dtype: int64

In [306]:
df['res_width'].count()

np.int64(1268)

In [308]:
df['res_width'] = pd.to_numeric(df['res_width'])

In [309]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 73 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
 68  has_foldable                 1268 non-null   int64
 69  res_category                 1268 non-null   category
 70  display_ppi                  1268 non-null   object
 71  display_pixels               1268 non-null   object
 72  res_width                    1268 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(6), int64(14), object(48)
memory usage: 689.9+ KB

In [317]:
df['res_height'] = df['display_pixels'].str.strip().str.split('x').str.get(1).str.split(' ').str.get(2)

In [318]:
df['res_height'].value_counts()

res_height
2400    307
1600    128
2340     92
2800     83
2412     81
2408     75
2392     58
1612     56
2712     36
1604     36
2640     21
2780     19
1650     17
2460     16
1640     16
2772     14
2796     13
3120     13
2556     11
2760     10
3200     10
3168     10
2436      9
2372      8
2622      8
2868      7
2404      7
1608      7
1570      7
2376      6
2532      6
3216      6
3088      5
2992      5
2664      4
2176      4
2720      4
2480      4
2448      4
2778      3
2184      3
2424      3
2736      3
2256      3
2670      3
2160      3
1080      3
2750      2
2856      2
2440      2
2700      2
2652      2
pi        2
3136      2
2520      2
2152      1
2076      1
2912      1
2373      1
2388      1
Name: count, dtype: int64

In [319]:
df[df['res_height'].str.contains('pi')]['display_pixels']

1055    1080 x 2520 pixels
1058    1080 x 2520 pixels
Name: display_pixels, dtype: object

In [320]:
df.loc[[1055,1058],'res_height'] = 2520

In [321]:
df['res_height'].value_counts()

res_height
2400    307
1600    128
2340     92
2800     83
2412     81
2408     75
2392     58
1612     56
2712     36
1604     36
2640     21
2780     19
1650     17
2460     16
1640     16
2772     14
2796     13
3120     13
2556     11
2760     10
3200     10
3168     10
2436      9
2372      8
2622      8
2868      7
2404      7
1608      7
1570      7
2376      6
2532      6
3216      6
3088      5
2992      5
2664      4
2176      4
2720      4
2480      4
2448      4
2778      3
2184      3
2424      3
2736      3
2256      3
2670      3
2160      3
1080      3
2750      2
2856      2
2440      2
2700      2
2652      2
2520      2
3136      2
2520      2
2152      1
2076      1
2912      1
2373      1
2388      1
Name: count, dtype: int64

In [322]:
df['res_height'] = pd.to_numeric(df['res_height'])

In [323]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 74 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
 68  has_foldable                 1268 non-null   int64
 69  res_category                 1268 non-null   category
 70  display_ppi                  1268 non-null   object
 71  display_pixels               1268 non-null   object
 72  res_width                    1268 non-null   int64
 73  res_height                   1268 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(6), int64(15), object(48)
memory usage: 699.8+ KB

In [324]:
# now drop display_pixels
df.drop(columns='display_pixels',inplace=True)

In [325]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 73 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     1268 non-null   int64
 1   model                        1268 non-null   object
 2   beebome_score                1268 non-null   int64
 3   rating                       1268 non-null   float64
 4   rating_count                 994 non-null    float64
 5   launch_on                    1268 non-null   datetime64[ns]
 6   old_price                    844 non-null    float64
 7   price                        1268 non-null   int64
 8   launch_price                 1268 non-null   int64
 9   display_type                 1268 non-null   object
 10  display_size                 1268 non-null   object
 11  display_res                  1268 non-null   object
 12  body_dimension               1268 non-null   object
 13  weight                       1268 non-null   object
 14  body_front                   1268 non-null   object
 15  body_back                    1238 non-null   object
 16  body_side                    1251 non-null   object
 17  build_quality                739 non-null    object
 18  ports                        1268 non-null   object
 19  ip_rating                    915 non-null    object
 20  speaker                      1265 non-null   object
 21  chipset                      1268 non-null   object
 22  cpu                          1268 non-null   object
 23  gpu                          1250 non-null   object
 24  main_cam                     1268 non-null   object
 25  main_cam2                    1214 non-null   object
 26  main_cam3                    631 non-null    object
 27  main_cam_features            1268 non-null   object
 28  main_video                   1239 non-null   object
 29  os                           1268 non-null   object
 30  software_updates             1228 non-null   object
 31  ai_features                  780 non-null    object
 32  front_cam                    1268 non-null   object
 33  front_cam_features           1026 non-null   object
 34  front_video                  1229 non-null   object
 35  battery                      1268 non-null   object
 36  charging                     1268 non-null   object
 37  storage                      1268 non-null   object
 38  ram                          1268 non-null   object
 39  sim                          1264 non-null   object
 40  tech                         1200 non-null   object
 41  2g                           1262 non-null   object
 42  3g                           1264 non-null   object
 43  4g                           1267 non-null   object
 44  5g                           1028 non-null   object
 45  speed                        1264 non-null   object
 46  wifi                         1268 non-null   object
 47  bluetooth                    1266 non-null   object
 48  positioning_system           1268 non-null   object
 49  nfc                          595 non-null    object
 50  finger_print                 1192 non-null   object
 51  sensors                      1268 non-null   object
 52  add_features                 469 non-null    object
 53  brand                        1268 non-null   category
 54  is_available                 1268 non-null   int64
 55  is_flipkart_available        1268 non-null   int64
 56  is_amazon_available          1268 non-null   int64
 57  is_official_available        1268 non-null   int64
 58  display_panel_type           1268 non-null   object
 59  display_panel_family         1268 non-null   category
 60  display_hz                   1268 non-null   int64
 61  display_dynamic_range        1268 non-null   category
 62  touch_sampling_rate          852 non-null    float64
 63  has_ltpo                     1268 non-null   int64
 64  has_anti_reflection_coating  1268 non-null   int64
 65  display_inches               1268 non-null   float64
 66  display_body_ratio           1036 non-null   float64
 67  has_curved                   1268 non-null   int64
 68  has_foldable                 1268 non-null   int64
 69  res_category                 1268 non-null   category
 70  display_ppi                  1268 non-null   object
 71  res_width                    1268 non-null   int64
 72  res_height                   1268 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(6), int64(15), object(47)
memory usage: 689.9+ KB