<a href="https://colab.research.google.com/github/rajeshxdatascience/SpecLens-AI/blob/main/SpecLens_AI_Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [194]:
import pandas as pd
import numpy as np

In [195]:
pd.set_option('display.max_columns',None)
pd.set_option('display.width',None)
pd.set_option('display.max_colwidth',None)

In [196]:
df = pd.read_csv('/content/new_smartphones_columns_for_ml.csv')

In [197]:
df.head()

,model_id,model,beebome_score,rating,rating_count,market_status,launch_on,old_price,price,launch_price,display_type,display_size,display_res,body_dimension,weight,body_front,body_back,body_side,build_quality,ports,ip_rating,speaker,chipset,cpu,gpu,main_cam,main_cam2,main_cam3,main_cam_features,main_video,os,software_updates,ai_features,front_cam,front_cam_features,front_video,battery,charging,storage,ram,sim,tech,2g,3g,4g,5g,speed,wifi,bluetooth,positioning_system,nfc,finger_print,sensors,add_features,flipkart_buy_link,amazon_buy_link,official_store_link
0,1,Apple iPhone 14 (6GB + 256GB),69,4.6,(321KRatings),In Stock,07 Sep 2022,"Was ₹56,999 2 day(s) ago Was ₹56,999 2 day(s) ago","₹64,900","₹79,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.1 inches, 90.2 cm², 86% Screen To Body Ratio","FHD+, 1170 x 2532 pixels, 19.5:9 (460 ppi), 8-bit colours, 82% DCI-P3, 1200 nits(Peak Brightness), 2000000:1 Contrast Ratio",146.7 x 71.5 x 7.8 mm,172 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR, Stereo Sound Recording",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","3279 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","256GB, NvMe","6GB, LPDDR4X",nano-SIM and eSIM,"5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100, CDMA2000 1xEV-DO (6 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-starlight-256-gb/p/itmaeda15697bb79?pid=MOBGHWFHBJGZYRZC&lid=LSTMOBGHWFHBJGZYRZCUALABX&marketplace=FLIPKART&q=iphone+14+&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=organic&iid=d16ab4a6-25f4-4cb9-8d77-ecbd3f8a6a54.MOBGHWFHBJGZYRZC.SEARCH&ppt=pp&ppn=pp&ssid=kueh4gc0g00000001729242962911&qH=e683ba9749683369&affid=contactbe1,https://www.amazon.in/dp/B0BDJS3MRM?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN
1,2,Apple iPhone 14 (6GB + 512GB),69,4.6,(321KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹89,900","₹79,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.1 inches, 90.2 cm², 86% Screen To Body Ratio","FHD+, 1170 x 2532 pixels, 19.5:9 (460 ppi), 8-bit colours, 82% DCI-P3, 1200 nits(Peak Brightness), 2000000:1 Contrast Ratio",146.7 x 71.5 x 7.8 mm,172 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR, Stereo Sound Recording",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","3279 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","512GB, NvMe","6GB, LPDDR4X",nano-SIM and eSIM,"5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100, CDMA2000 1xEV-DO (6 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-midnight-512-gb/p/itm01540a8ff03de?pid=MOBGHWFHBEMUZSBY&lid=LSTMOBGHWFHBEMUZSBYWJC9VQ&marketplace=FLIPKART&q=iphone+14+&store=tyy%2F4io&srno=s_1_5&otracker=search&otracker1=search&fm=organic&iid=d16ab4a6-25f4-4cb9-8d77-ecbd3f8a6a54.MOBGHWFHBEMUZSBY.SEARCH&ppt=pp&ppn=pp&ssid=kueh4gc0g00000001729242962911&qH=e683ba9749683369&affid=contactbe1,https://www.amazon.in/dp/B0BDJGX2XZ?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN
2,3,Apple iPhone 14 Plus (6GB + 256GB),72,4.6,(87KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹79,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","256GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-starlight-256-gb/p/itm8ee001dd954a2?pid=MOBGHWFHQGM9B4EU&lid=LSTMOBGHWFHQGM9B4EUGHBHUP&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_4&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHQGM9B4EU.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,NaN,NaN
3,4,Apple iPhone 14 Plus (6GB + 512GB),72,4.6,(87KRatings),Out of Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹99,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","512GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-blue-512-gb/p/itm9b829cc08a732?pid=MOBGHWFHKHPYMQX8&lid=LSTMOBGHWFHKHPYMQX8K7QHSJ&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_7&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHKHPYMQX8.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,NaN,NaN
4,5,Apple iPhone 14 Plus,72,4.6,(87KRatings),In Stock,07 Sep 2022,Lowest price since launch Lowest price since launch,"₹69,900","₹89,900","Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision","6.7 inches, 109.8 cm², 87.4% Screen To Body Ratio","FHD+, 1284 x 2778 pixels, 19.5:9 (458 ppi), 8-bit colours, 85% DCI-P3, 1200 nits(Peak Brightness), 800 nits(Typical Brightness), 2000000:1 Contrast Ratio",160.8 x 78.1 x 7.8 mm,203 grams,Glass,Glass,Aluminium Frame,Corning-made Glass,Lightning USB 2.0,IP68 (Dust and Water Resistant),Stereo Speakers,"Apple A15 Bionic (5 nm), 1287587 Antutu Score",Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard),Apple GPU (5-core graphics),"12 MP, f/1.5, 26mm (Wide-angle), Sensor-Shift OIS","12 MP, f/2.4, 13mm (Ultra-wide), 120°",NaN,"Auto Focus, Cinematic Mode, Digital Zoom, Dual LED Dual Tone Flash, HDR, Night Mode, OIS, Panorama, PDAF","4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 720p@30fps, Cinematic mode, Dolby Vision HDR (up to 60fps), HDR",iOS 16,5 year(s) of Software and Security updates,NaN,"12 MP, f/1.9, 23mm (Wide), 1/3.6"", PDAF","Auto Focus, Cinematic mode (4k@30fps)","1080p@25/30/60/120fps, 4K@24/25/30/60fps, gyro-EIS","4323 mAh, Lithium Ion (Non-removable)","20W (wired), Wireless Charging Supported50% in 30min (wired) (advertised)","128GB, NvMe","6GB, LPDDR4X","nano-SIM and eSIM (international), Dual eSIM (USA), Nano-SIM, dual stand-by (China)","5G, CDMA, EVDO, GSM, HSPA, LTE","1800, 1900, 850, 900 (4 bands)","UMTS/HSPA+/DC-HSDPA 850, 900, 1700(AWS), 1900, 2100 (5 bands)","LTE 1, 2, 3, 4, 5, 7, 8, 12, 13, 17, 18, 19, 20, 25, 26, 28, 30, 32, 34, 38, 39, 40, 41, 42, 46, 48, 66 (27 bands)","SA/NSA/Sub6 1, 2, 3, 5, 7, 8, 12, 20, 25, 26, 28, 30, 38, 40, 41, 48, 66, 70, 77, 78, 79 (21 bands)","5G, GSM, HSPA, LTE, UMTS","Wi-Fi 6 802.11 a/b/g/n/ac/ax, Hotspot, Wi-Fi Direct, Dual Band","5.3, A2DP, LE","BDS, GALILEO, GLONASS, GPS, QZSS",Supported,NaN,"Accelerometer, Barometer Sensor, Compass, Face ID, Gyroscope, Proximity Sensor, Ultra Wideband (UWB) Support",Linear Resonant Actuators,https://www.flipkart.com/apple-iphone-14-plus-starlight-128-gb/p/itmc922ddc8af349?pid=MOBGHWFHVCB2YZYR&lid=LSTMOBGHWFHVCB2YZYRBDOEVN&marketplace=FLIPKART&q=14+plus+iphone&store=tyy%2F4io&srno=s_1_3&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_ps&fm=organic&iid=463edb55-77b0-4ae0-b1cf-07d79dcb5f45.MOBGHWFHVCB2YZYR.SEARCH&ppt=pp&ppn=pp&ssid=74yvvmat5s0000001729233498497&qH=94ddc8675cffe2b2&affid=contactbe1,https://www.amazon.in/dp/B0BDJFTGK6?tag=beebomgadge0d-21&linkCode=ogv&th=1&psc=1,NaN

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 57 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    object
 5   market_status        1268 non-null   object
 6   launch_on            1268 non-null   object
 7   old_price            1149 non-null   object
 8   price                1268 non-null   object
 9   launch_price         1268 non-null   object
 10  display_type         1268 non-null   object
 11  display_size         1268 non-null   object
 12  display_res          1268 non-null   object
 13  body_dimension       1268 non-null   object
 14  weight               1268 non-null   object
 15  body_front           1268 non-null   object
 16  body_back            1238 non-null   object
 17  body_side            1251 non-null   object
 18  build_quality        739 non-null    object
 19  ports                1268 non-null   object
 20  ip_rating            915 non-null    object
 21  speaker              1265 non-null   object
 22  chipset              1268 non-null   object
 23  cpu                  1268 non-null   object
 24  gpu                  1250 non-null   object
 25  main_cam             1268 non-null   object
 26  main_cam2            1214 non-null   object
 27  main_cam3            631 non-null    object
 28  main_cam_features    1268 non-null   object
 29  main_video           1239 non-null   object
 30  os                   1268 non-null   object
 31  software_updates     1228 non-null   object
 32  ai_features          780 non-null    object
 33  front_cam            1268 non-null   object
 34  front_cam_features   1026 non-null   object
 35  front_video          1229 non-null   object
 36  battery              1268 non-null   object
 37  charging             1268 non-null   object
 38  storage              1268 non-null   object
 39  ram                  1268 non-null   object
 40  sim                  1264 non-null   object
 41  tech                 1200 non-null   object
 42  2g                   1262 non-null   object
 43  3g                   1264 non-null   object
 44  4g                   1267 non-null   object
 45  5g                   1028 non-null   object
 46  speed                1264 non-null   object
 47  wifi                 1268 non-null   object
 48  bluetooth            1266 non-null   object
 49  positioning_system   1268 non-null   object
 50  nfc                  595 non-null    object
 51  finger_print         1192 non-null   object
 52  sensors              1268 non-null   object
 53  add_features         469 non-null    object
 54  flipkart_buy_link    1085 non-null   object
 55  amazon_buy_link      724 non-null    object
 56  official_store_link  610 non-null    object
dtypes: float64(1), int64(2), object(54)
memory usage: 564.8+ KB

In [199]:
df['brand'] = df['model'].str.lower().str.split(' ').str.get(0)

In [200]:
df['brand'].value_counts()

brand
realme      231
samsung     196
vivo        177
oppo        100
redmi        93
iqoo         74
poco         70
infinix      61
oneplus      59
apple        54
motorola     40
moto         38
google       20
nothing      18
xiaomi       18
honor        10
asus          5
cmf           4
Name: count, dtype: int64

In [201]:
df.loc[df['brand'].str.contains('moto'),'brand'] = 'motorola'

In [202]:
df['brand'].value_counts()

brand
realme      231
samsung     196
vivo        177
oppo        100
redmi        93
motorola     78
iqoo         74
poco         70
infinix      61
oneplus      59
apple        54
google       20
nothing      18
xiaomi       18
honor        10
asus          5
cmf           4
Name: count, dtype: int64

In [203]:
df['brand'].count()

np.int64(1268)

In [204]:
df['brand'] = df['brand'].astype('category')

In [205]:
df['beebome_score'].value_counts()

beebome_score
80    57
73    45
84    41
74    41
68    37
      ..
47     4
28     3
26     3
29     2
22     1
Name: count, Length: 70, dtype: int64

In [206]:
df['rating'].value_counts()

rating
4.3    299
4.4    271
4.2    236
4.5    134
4.1     92
4.6     70
4.7     46
4.8     29
4.0     29
2.0     16
3.9     15
1.0     12
3.8      5
3.4      5
3.5      2
3.7      2
3.6      2
5.0      1
4.9      1
3.0      1
Name: count, dtype: int64

In [207]:
df['rating_count'] = df['rating_count'].str.lower().str.split('r').str.get(0)

In [208]:
df['rating_count'] = df['rating_count'].str.replace('(','')

In [209]:
df['rating_count'] = df['rating_count'].str.replace('k',"1000")

In [210]:
df['rating_count'] = df['rating_count'].astype('float64')

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   market_status        1268 non-null   object
 6   launch_on            1268 non-null   object
 7   old_price            1149 non-null   object
 8   price                1268 non-null   object
 9   launch_price         1268 non-null   object
 10  display_type         1268 non-null   object
 11  display_size         1268 non-null   object
 12  display_res          1268 non-null   object
 13  body_dimension       1268 non-null   object
 14  weight               1268 non-null   object
 15  body_front           1268 non-null   object
 16  body_back            1238 non-null   object
 17  body_side            1251 non-null   object
 18  build_quality        739 non-null    object
 19  ports                1268 non-null   object
 20  ip_rating            915 non-null    object
 21  speaker              1265 non-null   object
 22  chipset              1268 non-null   object
 23  cpu                  1268 non-null   object
 24  gpu                  1250 non-null   object
 25  main_cam             1268 non-null   object
 26  main_cam2            1214 non-null   object
 27  main_cam3            631 non-null    object
 28  main_cam_features    1268 non-null   object
 29  main_video           1239 non-null   object
 30  os                   1268 non-null   object
 31  software_updates     1228 non-null   object
 32  ai_features          780 non-null    object
 33  front_cam            1268 non-null   object
 34  front_cam_features   1026 non-null   object
 35  front_video          1229 non-null   object
 36  battery              1268 non-null   object
 37  charging             1268 non-null   object
 38  storage              1268 non-null   object
 39  ram                  1268 non-null   object
 40  sim                  1264 non-null   object
 41  tech                 1200 non-null   object
 42  2g                   1262 non-null   object
 43  3g                   1264 non-null   object
 44  4g                   1267 non-null   object
 45  5g                   1028 non-null   object
 46  speed                1264 non-null   object
 47  wifi                 1268 non-null   object
 48  bluetooth            1266 non-null   object
 49  positioning_system   1268 non-null   object
 50  nfc                  595 non-null    object
 51  finger_print         1192 non-null   object
 52  sensors              1268 non-null   object
 53  add_features         469 non-null    object
 54  flipkart_buy_link    1085 non-null   object
 55  amazon_buy_link      724 non-null    object
 56  official_store_link  610 non-null    object
 57  brand                1268 non-null   category
dtypes: category(1), float64(2), int64(2), object(53)
memory usage: 566.7+ KB

In [212]:
df['market_status'].value_counts()

market_status
In Stock        896
Out of Stock    372
Name: count, dtype: int64

In [213]:
def market(text):

  t = text.lower()

  if t == 'in stock':
    return 1
  elif t == 'out of stock':
    return 0

df['is_available'] = df['market_status'].apply(market)

In [214]:
df['is_available'].value_counts()

is_available
1    896
0    372
Name: count, dtype: int64

In [215]:
df.drop(columns='market_status',inplace=True)

In [216]:
df['launch_on']

0       07 Sep 2022
1       07 Sep 2022
2       07 Sep 2022
3       07 Sep 2022
4       07 Sep 2022
           ...
1263    07 Mar 2024
1264    11 Mar 2025
1265    11 Mar 2025
1266    09 May 2023
1267    09 May 2023
Name: launch_on, Length: 1268, dtype: object

In [217]:
df['launch_on'] = pd.to_datetime(df['launch_on'])

In [218]:
df['launch_on']

0      2022-09-07
1      2022-09-07
2      2022-09-07
3      2022-09-07
4      2022-09-07
          ...
1263   2024-03-07
1264   2025-03-11
1265   2025-03-11
1266   2023-05-09
1267   2023-05-09
Name: launch_on, Length: 1268, dtype: datetime64[ns]

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            1149 non-null   object
 7   price                1268 non-null   object
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(2), int64(3), object(51)
memory usage: 566.7+ KB

In [220]:
df['old_price'].value_counts()

old_price
Lowest price since launch Lowest price since launch      305
Was ₹7,999 2 month(s) ago Was ₹7,999 2 month(s) ago        8
Was ₹15,999 2 month(s) ago Was ₹15,999 2 month(s) ago      8
Was ₹22,999 2 month(s) ago Was ₹22,999 2 month(s) ago      7
Was ₹13,999 2 month(s) ago Was ₹13,999 2 month(s) ago      7
                                                        ...
Was ₹47,839 22 day(s) ago Was ₹47,839 22 day(s) ago        1
Was ₹25,999 2 month(s) ago Was ₹25,999 2 month(s) ago      1
Was ₹34,999 10 day(s) ago Was ₹34,999 10 day(s) ago        1
Was ₹23,799 5 day(s) ago Was ₹23,799 5 day(s) ago          1
Was ₹21,300 1 month(s) ago Was ₹21,300 1 month(s) ago      1
Name: count, Length: 667, dtype: int64

In [221]:
df['old_price'] = df['old_price'].str.lower().str.split(' ').str.get(1)

In [222]:
df.loc[df['old_price'] == 'price','old_price'] = np.nan

In [223]:
df['old_price'].value_counts(dropna=False)

old_price
NaN        424
₹11,999     18
₹9,999      16
₹22,999     16
₹10,999     15
          ...
₹13,898      1
₹12,754      1
₹11,874      1
₹11,450      1
₹22,319      1
Name: count, Length: 448, dtype: int64

In [224]:
df['old_price'] = df['old_price'].str.replace('₹','')

In [225]:
df['old_price'] = df['old_price'].str.replace(',','')

In [226]:
df['old_price'] = df['old_price'].astype('float')

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   object
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(3), object(50)
memory usage: 566.7+ KB

In [228]:
df['price'] = df['price'].str.replace('₹','')

In [229]:
df['price'] = df['price'].str.replace(',','')

In [230]:
df['price'] = df['price'].astype('int')

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   int64
 8   launch_price         1268 non-null   object
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(4), object(49)
memory usage: 566.7+ KB

In [232]:
df['launch_price'] = df['launch_price'].str.replace('₹','').str.replace(',','').astype(int)

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_id             1268 non-null   int64
 1   model                1268 non-null   object
 2   beebome_score        1268 non-null   int64
 3   rating               1268 non-null   float64
 4   rating_count         994 non-null    float64
 5   launch_on            1268 non-null   datetime64[ns]
 6   old_price            844 non-null    float64
 7   price                1268 non-null   int64
 8   launch_price         1268 non-null   int64
 9   display_type         1268 non-null   object
 10  display_size         1268 non-null   object
 11  display_res          1268 non-null   object
 12  body_dimension       1268 non-null   object
 13  weight               1268 non-null   object
 14  body_front           1268 non-null   object
 15  body_back            1238 non-null   object
 16  body_side            1251 non-null   object
 17  build_quality        739 non-null    object
 18  ports                1268 non-null   object
 19  ip_rating            915 non-null    object
 20  speaker              1265 non-null   object
 21  chipset              1268 non-null   object
 22  cpu                  1268 non-null   object
 23  gpu                  1250 non-null   object
 24  main_cam             1268 non-null   object
 25  main_cam2            1214 non-null   object
 26  main_cam3            631 non-null    object
 27  main_cam_features    1268 non-null   object
 28  main_video           1239 non-null   object
 29  os                   1268 non-null   object
 30  software_updates     1228 non-null   object
 31  ai_features          780 non-null    object
 32  front_cam            1268 non-null   object
 33  front_cam_features   1026 non-null   object
 34  front_video          1229 non-null   object
 35  battery              1268 non-null   object
 36  charging             1268 non-null   object
 37  storage              1268 non-null   object
 38  ram                  1268 non-null   object
 39  sim                  1264 non-null   object
 40  tech                 1200 non-null   object
 41  2g                   1262 non-null   object
 42  3g                   1264 non-null   object
 43  4g                   1267 non-null   object
 44  5g                   1028 non-null   object
 45  speed                1264 non-null   object
 46  wifi                 1268 non-null   object
 47  bluetooth            1266 non-null   object
 48  positioning_system   1268 non-null   object
 49  nfc                  595 non-null    object
 50  finger_print         1192 non-null   object
 51  sensors              1268 non-null   object
 52  add_features         469 non-null    object
 53  flipkart_buy_link    1085 non-null   object
 54  amazon_buy_link      724 non-null    object
 55  official_store_link  610 non-null    object
 56  brand                1268 non-null   category
 57  is_available         1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(5), object(48)
memory usage: 566.7+ KB

In [234]:
df['is_flipkart_available'] = df['flipkart_buy_link'].notna().astype('int')

In [235]:
df['is_flipkart_available'].value_counts()

is_flipkart_available
1    1085
0     183
Name: count, dtype: int64

In [236]:
df['is_amazon_available'] = df['amazon_buy_link'].notna().astype('int')

In [237]:
df['is_amazon_available'].value_counts()

is_amazon_available
1    724
0    544
Name: count, dtype: int64

In [238]:
df['is_official_available'] = df['official_store_link'].notna().astype('int')

In [239]:
df['is_official_available'].value_counts()

is_official_available
0    658
1    610
Name: count, dtype: int64

In [240]:
df.drop(columns=['flipkart_buy_link','amazon_buy_link','official_store_link'],inplace=True)

In [241]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 58 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model_id               1268 non-null   int64
 1   model                  1268 non-null   object
 2   beebome_score          1268 non-null   int64
 3   rating                 1268 non-null   float64
 4   rating_count           994 non-null    float64
 5   launch_on              1268 non-null   datetime64[ns]
 6   old_price              844 non-null    float64
 7   price                  1268 non-null   int64
 8   launch_price           1268 non-null   int64
 9   display_type           1268 non-null   object
 10  display_size           1268 non-null   object
 11  display_res            1268 non-null   object
 12  body_dimension         1268 non-null   object
 13  weight                 1268 non-null   object
 14  body_front             1268 non-null   object
 15  body_back              1238 non-null   object
 16  body_side              1251 non-null   object
 17  build_quality          739 non-null    object
 18  ports                  1268 non-null   object
 19  ip_rating              915 non-null    object
 20  speaker                1265 non-null   object
 21  chipset                1268 non-null   object
 22  cpu                    1268 non-null   object
 23  gpu                    1250 non-null   object
 24  main_cam               1268 non-null   object
 25  main_cam2              1214 non-null   object
 26  main_cam3              631 non-null    object
 27  main_cam_features      1268 non-null   object
 28  main_video             1239 non-null   object
 29  os                     1268 non-null   object
 30  software_updates       1228 non-null   object
 31  ai_features            780 non-null    object
 32  front_cam              1268 non-null   object
 33  front_cam_features     1026 non-null   object
 34  front_video            1229 non-null   object
 35  battery                1268 non-null   object
 36  charging               1268 non-null   object
 37  storage                1268 non-null   object
 38  ram                    1268 non-null   object
 39  sim                    1264 non-null   object
 40  tech                   1200 non-null   object
 41  2g                     1262 non-null   object
 42  3g                     1264 non-null   object
 43  4g                     1267 non-null   object
 44  5g                     1028 non-null   object
 45  speed                  1264 non-null   object
 46  wifi                   1268 non-null   object
 47  bluetooth              1266 non-null   object
 48  positioning_system     1268 non-null   object
 49  nfc                    595 non-null    object
 50  finger_print           1192 non-null   object
 51  sensors                1268 non-null   object
 52  add_features           469 non-null    object
 53  brand                  1268 non-null   category
 54  is_available           1268 non-null   int64
 55  is_flipkart_available  1268 non-null   int64
 56  is_amazon_available    1268 non-null   int64
 57  is_official_available  1268 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(3), int64(8), object(45)
memory usage: 566.7+ KB

In [242]:
df['display_type'].sample(10)

668                                                    IPS LCD, 120 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
245                                                                                  AMOLED, 60 Hz Refresh Rate, SDR
1004                                              Super AMOLED, 120 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
1193                                                                                IPS LCD, 60 Hz Refresh Rate, SDR
855                                    Pro HDR AMOLED, 120 Hz Refresh Rate, Dolby Vision, 240 Hz Touch Sampling Rate
66                                                                                    OLED, 120 Hz Refresh Rate, HDR
75                                                                                    OLED, 120 Hz Refresh Rate, HDR
1263    Dynamic AMOLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 240 Hz Touch Sampling Rate, Anti Reflection Coating
1162                                                                             AMOLED, 120 Hz Refresh Rate, HDR10+
310                                                  AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [243]:
# creating column for display_panel_type

df['display_panel_type'] = df['display_type'].str.lower().str.split(',').str.get(0)

In [244]:
df['display_panel_type'].value_counts(dropna=False)

display_panel_type
amoled                          324
ips lcd                         310
super amoled                    105
lcd                              68
dynamic 2x amoled                60
super retina xdr oled            49
oled                             40
proxdr amoled                    32
p-oled                           30
pls lcd                          27
dot amoled                       25
hdr amoled                       23
e4 amoled                        17
dot ips lcd                      16
fluid amoled                     10
e5 amoled                         9
ultra smooth display ips lcd      9
super actua oled                  8
smooth display amoled             8
pro hdr amoled                    8
turbo amoled                      7
proxdr oled                       7
ultra amoled                      7
e6 amoled                         6
flow amoled                       6
q10+ amoled                       6
3d amoled amoled                  5
super retina xdr amoled           5
q10 amoled                        4
tft lcd                           4
hyperglow amoled                  3
e7 amoled                         3
fluid oled                        2
tft ips                           2
ips                               2
led                               2
u8 amoled                         2
ultra smooth display amoled       2
ultra smooth display lcd          2
trinity engine amoled             2
boundless display ips lcd         2
smooth display oled               1
true colour display amoled        1
dynamic ips lcd                   1
hdr oled                          1
super actua ips lcd               1
ips a-si                          1
smooth display ips lcd            1
smooth display lcd                1
dynamic amoled                    1
Name: count, dtype: int64

In [245]:
# there are more than 50+ category so we have to make new column

def display_panel_family(text):

    t = text.lower()

    if 'amoled' in t:
      return 'amoled'

    if 'oled' in t and 'amoled' not in t:
      return 'oled'

    if 'ips lcd' in t or ('ips' in t and 'tft' not in t):
      return 'ips lcd'

    if 'tft' in t:
      return 'tft'

    if 'led' in t:
      return 'led'

    if 'lcd' in t:
      return 'lcd'

    return 'unknown'

df['display_panel_family'] = df['display_panel_type'].apply(display_panel_family)

In [246]:
df['display_panel_family'].value_counts()

display_panel_family
amoled     681
ips lcd    343
oled       138
lcd         98
tft          6
led          2
Name: count, dtype: int64

In [247]:
# convert display_panel_family from object dtypes to category

df['display_panel_family'] = df['display_panel_family'].astype('category')

In [248]:
df['display_type'].sample(10)

64                                                                      Super Actua OLED, 120 Hz Refresh Rate, LTPO, HDR10+
545                                                            AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
731                                                                                          OLED, 120 Hz Refresh Rate, SDR
792                                                                                        IPS LCD, 90 Hz Refresh Rate, SDR
1148                                                        AMOLED, 120 Hz Refresh Rate, HDR10+, 480 Hz Touch Sampling Rate
978                                                                                        PLS LCD, 90 Hz Refresh Rate, SDR
18                                                                  Super Retina XDR OLED, 60 Hz Refresh Rate, Dolby Vision
832                                                           IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
1178                                                                         Q10+ AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+
9       Super Retina XDR OLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 360 Hz Touch Sampling Rate, Anti Reflection Coating
Name: display_type, dtype: object

In [249]:
# creating new col from display_type name display_hz

df['display_hz'] = df['display_type'].str.lower().str.split(',').str.get(1)

In [250]:
df['display_hz'] = df['display_hz'].str.split(' ').str.get(1)

In [251]:
df['display_hz'].value_counts()

display_hz
120    781
90     274
60     119
144     81
165     12
sdr      1
Name: count, dtype: int64

In [252]:
df[df['display_hz'].str.contains('sdr')]

,model_id,model,beebome_score,rating,rating_count,launch_on,old_price,price,launch_price,display_type,display_size,display_res,body_dimension,weight,body_front,body_back,body_side,build_quality,ports,ip_rating,speaker,chipset,cpu,gpu,main_cam,main_cam2,main_cam3,main_cam_features,main_video,os,software_updates,ai_features,front_cam,front_cam_features,front_video,battery,charging,storage,ram,sim,tech,2g,3g,4g,5g,speed,wifi,bluetooth,positioning_system,nfc,finger_print,sensors,add_features,brand,is_available,is_flipkart_available,is_amazon_available,is_official_available,display_panel_type,display_panel_family,display_hz
228,229,Moto E13 (8GB + 128GB),50,4.1,371000.0,2023-02-08,NaN,9299,6999,"IPS LCD, SDR","6.5 inches, 102 cm², 89.2% Screen To Body Ratio","HD+, 720 x 1600 pixels, 20:9 (269 ppi), 8-bit colours",164.19 x 74.95 x 8.47 mm,179.5 grams,Glass,Plastic,Plastic Frame,Plastic Material,"USB Type-C 2.0, 3.5mm Headphone Jack, OTG",IP52 (Dust and Splash Resistant),Mono Speaker,"Unisoc T606 (12 nm), 246197 Antutu Score",Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55),Mali-G57 MP1,"13 MP, f/2.2, (Wide-angle), 1.12 µm, PDAF",NaN,NaN,"HDR, LED Flash, Panorama, Pro Mode",1080p@30fps,"Android Go 13, Motorola MyUx",NaN,"AI Beauty, AI Camera, Auto Smile Capture","5 MP, f/2.2, (Wide-angle), 1.12 µm, 1/5""","AI Beauty Mode, HDR Photos, Portrait Mode",1080p@30fps,"5000 mAh, Lithium Polymer (Non-removable)",10W (wired),"128GB, eMMC 5.1","8GB, LPDDR4X",Hybrid Dual SIM (2 Nano SIMs + 1 microSD),"GSM, HSPA, LTE","3, 5, 8 (3 bands)","1, 5, 8 (3 bands)","1, 3, 5, 7, 8, 20, 28, 38, 40, 41 (10 bands)",NaN,"GSM, HSPA, LTE","Wi-Fi 5 802.11 a/b/g/n/ac, Hotspot, Dual Band","A2DP, AAC, LE, SBC","A-GPS, GALILEO, GLONASS, GPS, LTEPP, SUPL",NaN,NaN,"Accelerometer, Ambient Light Sensor, Proximity Sensor",NaN,motorola,0,0,1,0,ips lcd,ips lcd,sdr

In [253]:
# this model display_hz is not available so fill nan
df.loc[228,'display_hz'] = np.nan

In [254]:
df['display_hz'].value_counts()

display_hz
120    781
90     274
60     119
144     81
165     12
Name: count, dtype: int64

In [255]:
# converting data types of diplay_hz to numeric

df['display_hz'] = pd.to_numeric(df['display_hz'],errors='coerce')

In [256]:
df['display_hz'].dtypes

dtype('float64')

In [292]:
df['display_type'].sample(20)

1032                             Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate
401                                                                              IPS LCD, 90 Hz Refresh Rate, SDR
902                                                                              IPS LCD, 60 Hz Refresh Rate, SDR
985                                             Super AMOLED, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
211                                              AMOLED, 120 Hz Refresh Rate, HDR10+, 1200 Hz Touch Sampling Rate
361                                           HDR AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
989                                                                         Super AMOLED, 90 Hz Refresh Rate, SDR
541                                              Dot AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
422                                                    OLED, 120 Hz Refresh Rate, HDR, 240 Hz Touch Sampling Rate
1038    Dynamic 2X AMOLED, 120 Hz Refresh Rate, LTPO, HDR10+, 240 Hz Touch Sampling Rate, Anti Reflection Coating
1097                                              AMOLED, 120 Hz Refresh Rate, HDR10+, 480 Hz Touch Sampling Rate
144                                                  IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
474                                                 OLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
344                            ProXDR AMOLED, 120 Hz Refresh Rate, LTPO, Dolby Vision, 360 Hz Touch Sampling Rate
476                                               AMOLED, 120 Hz Refresh Rate, HDR10+, 240 Hz Touch Sampling Rate
242                                                 IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
351                                                           HDR AMOLED, 165 Hz Refresh Rate, LTPO, Dolby Vision
921                                            Super AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
440                                 Trinity Engine AMOLED, 120 Hz Refresh Rate, HDR10, 240 Hz Touch Sampling Rate
556                               Boundless Display IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [293]:
# keeping only hdr10+ , hd10 and sdr
def display_dynamic_range(text):

  t = text

  if 'Dolby Vision' in t or 'HDR10+' in t or 'ProXDR' in t:
    return 'HDR10+'
  elif 'HDR' in t or 'HDR10' in t or 'Pro HDR' in t:
    return 'HDR'

  return 'SDR'

df['display_dynamic_range'] = df['display_type'].apply(display_dynamic_range)

In [296]:
df['display_dynamic_range'].value_counts(dropna=False)

display_dynamic_range
SDR       660
HDR10+    521
HDR        87
Name: count, dtype: int64

In [298]:
df['display_dynamic_range'].count()

np.int64(1268)

In [302]:
df[df['display_dynamic_range'].str.contains('SDR')]['display_type'].sample(20)

525                                                                AMOLED, 90 Hz Refresh Rate, SDR
599    AMOLED, 120 Hz Refresh Rate, LTPO, SDR, 240 Hz Touch Sampling Rate, Anti Reflection Coating
131                                   AMOLED, 144 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
733                                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
788                                                               IPS LCD, 90 Hz Refresh Rate, SDR
664                                   IPS LCD, 90 Hz Refresh Rate, SDR, 180 Hz Touch Sampling Rate
971                                                               PLS LCD, 60 Hz Refresh Rate, SDR
976                                                               PLS LCD, 90 Hz Refresh Rate, SDR
632                                   IPS LCD, 60 Hz Refresh Rate, SDR, 120 Hz Touch Sampling Rate
787                                                               IPS LCD, 90 Hz Refresh Rate, SDR
577                                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
544                                   AMOLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
759                                     OLED, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
151                                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
530                                  IPS LCD, 144 Hz Refresh Rate, SDR, 288 Hz Touch Sampling Rate
896                                                               PLS LCD, 60 Hz Refresh Rate, SDR
800                                   IPS LCD, 60 Hz Refresh Rate, SDR, 120 Hz Touch Sampling Rate
425    AMOLED, 120 Hz Refresh Rate, LTPO, SDR, 240 Hz Touch Sampling Rate, Anti Reflection Coating
749                                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
774                                  IPS LCD, 120 Hz Refresh Rate, SDR, 240 Hz Touch Sampling Rate
Name: display_type, dtype: object

In [303]:
# converting display_dynamic_range into category
df['display_dynamic_range'] = df['display_dynamic_range'].astype('category')

In [304]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1268 entries, 0 to 1267
Data columns (total 62 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model_id               1268 non-null   int64
 1   model                  1268 non-null   object
 2   beebome_score          1268 non-null   int64
 3   rating                 1268 non-null   float64
 4   rating_count           994 non-null    float64
 5   launch_on              1268 non-null   datetime64[ns]
 6   old_price              844 non-null    float64
 7   price                  1268 non-null   int64
 8   launch_price           1268 non-null   int64
 9   display_type           1268 non-null   object
 10  display_size           1268 non-null   object
 11  display_res            1268 non-null   object
 12  body_dimension         1268 non-null   object
 13  weight                 1268 non-null   object
 14  body_front             1268 non-null   object
 15  body_back              1238 non-null   object
 16  body_side              1251 non-null   object
 17  build_quality          739 non-null    object
 18  ports                  1268 non-null   object
 19  ip_rating              915 non-null    object
 20  speaker                1265 non-null   object
 21  chipset                1268 non-null   object
 22  cpu                    1268 non-null   object
 23  gpu                    1250 non-null   object
 24  main_cam               1268 non-null   object
 25  main_cam2              1214 non-null   object
 26  main_cam3              631 non-null    object
 27  main_cam_features      1268 non-null   object
 28  main_video             1239 non-null   object
 29  os                     1268 non-null   object
 30  software_updates       1228 non-null   object
 31  ai_features            780 non-null    object
 32  front_cam              1268 non-null   object
 33  front_cam_features     1026 non-null   object
 34  front_video            1229 non-null   object
 35  battery                1268 non-null   object
 36  charging               1268 non-null   object
 37  storage                1268 non-null   object
 38  ram                    1268 non-null   object
 39  sim                    1264 non-null   object
 40  tech                   1200 non-null   object
 41  2g                     1262 non-null   object
 42  3g                     1264 non-null   object
 43  4g                     1267 non-null   object
 44  5g                     1028 non-null   object
 45  speed                  1264 non-null   object
 46  wifi                   1268 non-null   object
 47  bluetooth              1266 non-null   object
 48  positioning_system     1268 non-null   object
 49  nfc                    595 non-null    object
 50  finger_print           1192 non-null   object
 51  sensors                1268 non-null   object
 52  add_features           469 non-null    object
 53  brand                  1268 non-null   category
 54  is_available           1268 non-null   int64
 55  is_flipkart_available  1268 non-null   int64
 56  is_amazon_available    1268 non-null   int64
 57  is_official_available  1268 non-null   int64
 58  display_panel_type     1268 non-null   object
 59  display_panel_family   1268 non-null   category
 60  display_hz             1267 non-null   float64
 61  display_dynamic_range  1268 non-null   category
dtypes: category(3), datetime64[ns](1), float64(4), int64(8), object(46)
memory usage: 589.3+ KB